<template>
  <div class="gva-form-box sources-page">
    <div class="page-head"><div><h2>论坛来源</h2><p>维护论坛采集来源和访问节流策略。</p></div><el-button type="primary" :icon="Plus" @click="openCreate">新增来源</el-button></div>
    <div class="toolbar"><el-input v-model="keyword" clearable placeholder="来源名称或地址" @keyup.enter="load" /><el-select v-model="enabled" clearable placeholder="状态" @change="load"><el-option label="启用" value="true" /><el-option label="停用" value="false" /></el-select><el-button :icon="Search" @click="load">查询</el-button></div>
    <el-table v-loading="loading" :data="rows" border><el-table-column label="来源 ID" min-width="170"><template #default="{row}"><code>{{ row.id }}</code></template></el-table-column><el-table-column prop="sourceName" label="名称" min-width="150" /><el-table-column prop="baseUrl" label="地址" min-width="260" show-overflow-tooltip /><el-table-column prop="requestCharset" label="编码" width="100" /><el-table-column label="Cookie" width="110"><template #default="{row}">{{ row.cookieConfigured ? '已配置' : '未配置' }}</template></el-table-column><el-table-column prop="requestIntervalMs" label="间隔（毫秒）" width="130" /><el-table-column prop="enabled" label="状态" width="90"><template #default="{row}">{{ row.enabled ? '启用' : '停用' }}</template></el-table-column><el-table-column label="操作" width="240"><template #default="{row}"><el-button link type="primary" :icon="Connection" :loading="checkingId === row.id" @click="checkSource(row)">检查</el-button><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
    <div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @size-change="load" @current-change="load" /></div>
    <el-dialog v-model="dialog" :title="editing ? '编辑论坛来源' : '新增论坛来源'" width="560px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-form-item label="来源名称" prop="sourceName"><el-input v-model="form.sourceName" maxlength="100" /></el-form-item><el-form-item label="基础地址" prop="baseUrl"><el-input v-model="form.baseUrl" maxlength="500" /></el-form-item><el-form-item label="响应编码" prop="requestCharset"><el-input v-model="form.requestCharset" maxlength="40" /></el-form-item><el-form-item label="Cookie 环境变量引用" prop="cookieSecretRef"><el-input v-model="form.cookieSecretRef" maxlength="128" placeholder="MOONBOOK_FORUM_COOKIE_EXAMPLE" /></el-form-item><el-form-item label="User-Agent"><el-input v-model="form.userAgent" maxlength="500" /></el-form-item><el-form-item label="请求间隔（毫秒）" prop="requestIntervalMs"><el-input v-model="form.requestIntervalMs" inputmode="numeric" /></el-form-item><el-form-item label="排序" prop="sortOrder"><el-input v-model="form.sortOrder" inputmode="numeric" /></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled" /></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" maxlength="500" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import { reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Connection, Plus, Search } from '@element-plus/icons-vue'
import { listCrawlSources, createCrawlSource, checkCrawlSource, updateCrawlSource, deleteCrawlSource } from '@/api/novel/crawlSources'
defineOptions({ name: 'NovelCrawlSources' })
const rows=ref([]);const total=ref(0);const page=ref(1);const pageSize=ref(20);const keyword=ref('');const enabled=ref('');const loading=ref(false);const dialog=ref(false);const editing=ref(false);const saving=ref(false);const checkingId=ref('');const formRef=ref();const sourceId=ref('');const form=reactive({sourceName:'',baseUrl:'',requestCharset:'UTF-8',cookieSecretRef:'',userAgent:'',requestIntervalMs:'1000',enabled:true,sortOrder:'0',remark:''})
const rules={sourceName:[{required:true,message:'请输入来源名称',trigger:'blur'}],baseUrl:[{required:true,type:'url',message:'请输入合法 URL',trigger:'blur'}],requestCharset:[{required:true,message:'请输入响应编码',trigger:'blur'}],cookieSecretRef:[{pattern:/^$|^MOONBOOK_FORUM_COOKIE_[A-Z0-9_]+$/,message:'请输入合法的 Cookie 环境变量引用',trigger:'blur'}],requestIntervalMs:[{required:true,pattern:/^[1-9]\d{2,7}$/,message:'请输入 100-86400000 的整数',trigger:'blur'}],sortOrder:[{required:true,pattern:/^\d+$/,message:'请输入非负整数',trigger:'blur'}]}
const checkMessages={AUTH_FAILED:'认证失败',REDIRECT_BLOCKED:'重定向被拒绝',TIMEOUT:'连接超时',RESPONSE_TOO_LARGE:'响应过大',DNS_FAILED:'域名解析失败',CONNECT_FAILED:'连接失败',HTTP_ERROR:'HTTP 状态异常',TARGET_BLOCKED:'目标地址不允许',SECRET_NOT_CONFIGURED:'Cookie Secret 未配置'}
const load=async()=>{loading.value=true;try{const res=await listCrawlSources({keyword:keyword.value,enabled:enabled.value,page:page.value,pageSize:pageSize.value});rows.value=res.data?.list||[];total.value=res.data?.total||0}finally{loading.value=false}}
const openCreate=()=>{editing.value=false;sourceId.value='';Object.assign(form,{sourceName:'',baseUrl:'',requestCharset:'UTF-8',cookieSecretRef:'',userAgent:'',requestIntervalMs:'1000',enabled:true,sortOrder:'0',remark:''});dialog.value=true}
const openEdit=(row)=>{editing.value=true;sourceId.value=row.id;Object.assign(form,{sourceName:row.sourceName,baseUrl:row.baseUrl,requestCharset:row.requestCharset,cookieSecretRef:row.cookieSecretRef||'',userAgent:row.userAgent,requestIntervalMs:row.requestIntervalMs,enabled:row.enabled,sortOrder:row.sortOrder,remark:row.remark});dialog.value=true}
const checkSource=async(row)=>{checkingId.value=row.id;try{const res=await checkCrawlSource(row.id);const result=res.data||{};if(result.ok){ElMessage.success(`连接正常（${result.elapsedMs} 毫秒）`);return}ElMessage.warning(checkMessages[result.code]||'连接检查失败')}finally{checkingId.value=''}}
const save=async()=>{if(!(await formRef.value?.validate().catch(()=>false)))return;saving.value=true;try{if(editing.value)await updateCrawlSource(sourceId.value,{...form});else await createCrawlSource({...form});ElMessage.success('保存成功');dialog.value=false;load()}finally{saving.value=false}}
const remove=async(row)=>{try{await ElMessageBox.confirm(`确定删除来源“${row.sourceName}”吗？`,'删除确认',{type:'warning'});await deleteCrawlSource(row.id);ElMessage.success('删除成功');load()}catch{ElMessage.info('已取消删除')}}
load()
</script>
<style scoped>.sources-page{padding:20px}.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.page-head h2{margin:0}.page-head p{margin:6px 0 0;color:var(--el-text-color-secondary)}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar .el-input{max-width:300px}.pager{display:flex;justify-content:flex-end;margin-top:16px}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}</style>
