<template>
  <div class="p-4">
    <div class="gva-search-box clean-toolbar">
      <el-tabs v-model="tab"><el-tab-pane label="清洗任务" name="tasks" /><el-tab-pane label="结果审核" name="results" /></el-tabs>
      <div><el-button :icon="Setting" @click="openConfig">配置</el-button><el-button type="primary" :icon="Plus" @click="startVisible = true">启动任务</el-button></div>
    </div>
    <div class="gva-table-box">
      <template v-if="tab === 'tasks'">
        <el-table v-loading="loading" :data="tasks" row-key="id">
          <el-table-column label="任务 ID" width="180"><template #default="{ row }"><code>{{ row.id }}</code></template></el-table-column>
          <el-table-column prop="bookName" label="书籍" min-width="180" show-overflow-tooltip />
          <el-table-column prop="status" label="状态" width="100"><template #default="{ row }"><el-tag :type="taskType(row.status)">{{ taskLabel(row.status) }}</el-tag></template></el-table-column>
          <el-table-column label="进度" width="150"><template #default="{ row }">{{ row.processedCount }} / {{ row.totalCount }}</template></el-table-column>
          <el-table-column prop="successCount" label="成功" width="75" /><el-table-column prop="discardCount" label="丢弃" width="75" /><el-table-column prop="failCount" label="失败" width="75" />
          <el-table-column prop="errorSummary" label="错误摘要" min-width="180" show-overflow-tooltip />
          <el-table-column label="操作" width="100" fixed="right"><template #default="{ row }"><el-tooltip v-if="row.status === 'running'" content="停止"><el-button link type="danger" :icon="VideoPause" @click="stop(row.id)" /></el-tooltip><el-tooltip v-else content="续跑"><el-button link type="primary" :icon="RefreshRight" @click="resume(row.id)" /></el-tooltip></template></el-table-column>
        </el-table>
      </template>
      <template v-else>
        <el-table v-loading="loading" :data="results" row-key="id">
          <el-table-column label="结果 ID" width="180"><template #default="{ row }"><code>{{ row.id }}</code></template></el-table-column><el-table-column prop="bookName" label="书籍" min-width="150" /><el-table-column prop="chapterName" label="章节" min-width="190" show-overflow-tooltip /><el-table-column prop="contentType" label="类型" width="110" /><el-table-column prop="cleanedWordCount" label="清洗字数" width="90" /><el-table-column prop="status" label="状态" width="130" />
          <el-table-column label="操作" width="120" fixed="right"><template #default="{ row }"><el-tooltip content="审核"><el-button link type="primary" :icon="View" @click="openReview(row.id)" /></el-tooltip><el-tooltip v-if="['failed','discarded','manual_discarded'].includes(row.status)" content="重洗"><el-button link type="warning" :icon="RefreshRight" @click="reclean(row.id)" /></el-tooltip></template></el-table-column>
        </el-table>
      </template>
      <div class="gva-pagination"><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" :total="total" layout="total, sizes, prev, pager, next" @change="load" /></div>
    </div>

    <el-dialog v-model="startVisible" title="启动章节清洗" width="480px"><el-form label-width="90px"><el-form-item label="书籍 ID"><el-input v-model="startForm.bookId" inputmode="numeric" placeholder="请输入完整书籍 ID" /></el-form-item><el-form-item label="强制重洗"><el-switch v-model="startForm.forceReclean" /></el-form-item><el-form-item label="操作人"><el-input v-model="startForm.operatorName" maxlength="64" /></el-form-item></el-form><template #footer><el-button @click="startVisible=false">取消</el-button><el-button type="primary" @click="start">启动</el-button></template></el-dialog>
    <el-dialog v-model="configVisible" title="章节清洗配置" width="min(760px, 94vw)"><el-form label-width="150px"><el-form-item label="启用"><el-switch v-model="config.enabled" /></el-form-item><el-form-item label="AI 配置"><el-select v-model="config.aiConfigId" class="w-full"><el-option v-for="item in aiOptions" :key="item.id" :label="`${item.configName} / ${item.currentModelName}`" :value="item.id" /></el-select></el-form-item><el-form-item label="拒答备用配置"><el-select v-model="config.refusalFallbackAiConfigId" clearable class="w-full"><el-option v-for="item in aiOptions" :key="item.id" :label="`${item.configName} / ${item.currentModelName}`" :value="item.id" /></el-select></el-form-item><el-form-item label="系统提示词"><el-input v-model="config.systemPrompt" type="textarea" :rows="5" /></el-form-item><div class="config-grid"><el-form-item label="温度"><el-input-number v-model="config.temperature" :min="0" :max="2" :step="0.1" /></el-form-item><el-form-item label="最大输出 Token"><el-input-number v-model="config.maxTokens" :min="0" /></el-form-item><el-form-item label="超时（秒）"><el-input-number v-model="config.timeoutSeconds" :min="1" :max="1800" /></el-form-item><el-form-item label="最低章节字数"><el-input-number v-model="config.minChapterWordCount" :min="0" /></el-form-item><el-form-item label="最低保留比例"><el-input-number v-model="config.minCleanedTextPercent" :min="0" :max="100" /></el-form-item><el-form-item label="原文成功阈值"><el-input-number v-model="config.autoSuccessWordCount" :min="0" /></el-form-item><el-form-item label="失败重试"><el-input-number v-model="config.retryCount" :min="0" :max="20" /></el-form-item><el-form-item label="失败后继续"><el-switch v-model="config.continueOnFailure" /></el-form-item></div><el-form-item label="请求间隔（毫秒）"><el-input-number v-model="config.requestIntervalMs" :min="0" :max="600000" /></el-form-item></el-form><template #footer><el-button @click="configVisible=false">取消</el-button><el-button type="primary" @click="saveConfig">保存</el-button></template></el-dialog>
    <el-dialog v-model="reviewVisible" title="清洗结果审核" width="min(1000px, 96vw)" top="4vh"><el-descriptions v-if="review" :column="2" border><el-descriptions-item label="书籍">{{ review.bookName }}</el-descriptions-item><el-descriptions-item label="章节">{{ review.chapterName }}</el-descriptions-item><el-descriptions-item label="AI 类型">{{ review.contentType }}</el-descriptions-item><el-descriptions-item label="置信度">{{ review.confidence ?? '-' }}</el-descriptions-item></el-descriptions><div v-if="review" class="review-grid"><el-form-item label="原文"><el-input :model-value="review.originalText" type="textarea" :rows="18" readonly /></el-form-item><el-form-item label="清洗稿"><el-input v-model="review.cleanedText" type="textarea" :rows="18" /></el-form-item></div><template #footer><el-button type="danger" @click="submitReview('manual_discarded')">丢弃章节</el-button><el-button type="primary" @click="submitReview('success')">采用清洗稿</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import { reactive, ref, watch } from 'vue';import { Plus, RefreshRight, Setting, VideoPause, View } from '@element-plus/icons-vue';import { ElMessage, ElMessageBox } from 'element-plus';import { listEnabledAIConfigs } from '@/api/novel/aiConfigs';import { getChapterCleanConfig,getChapterCleanResult,listChapterCleanResults,listChapterCleanTasks,recleanChapterCleanResult,resumeChapterCleanTask,reviewChapterCleanResult,saveChapterCleanConfig,startChapterCleanTask,stopChapterCleanTask } from '@/api/novel/chapterClean';import { assertLongId } from '@/utils/longId'
defineOptions({name:'NovelChapterClean'});const tab=ref('tasks'),loading=ref(false),tasks=ref([]),results=ref([]),total=ref(0),query=reactive({page:1,pageSize:20});const startVisible=ref(false),startForm=reactive({bookId:'',forceReclean:false,operatorName:''});const configVisible=ref(false),config=reactive({}),aiOptions=ref([]);const reviewVisible=ref(false),review=ref(null)
const load=async()=>{loading.value=true;try{const res=tab.value==='tasks'?await listChapterCleanTasks(query):await listChapterCleanResults(query);if(tab.value==='tasks')tasks.value=res.data?.list||[];else results.value=res.data?.list||[];total.value=res.data?.total||0}finally{loading.value=false}};watch(tab,()=>{query.page=1;load()});const start=async()=>{await startChapterCleanTask({...startForm,bookId:assertLongId(startForm.bookId)});startVisible.value=false;ElMessage.success('任务已启动');load()};const stop=async id=>{await ElMessageBox.confirm('确定停止该任务吗？','停止任务',{type:'warning'});await stopChapterCleanTask(assertLongId(id));load()};const resume=async id=>{await resumeChapterCleanTask(assertLongId(id));load()};const openConfig=async()=>{const [cfg,options]=await Promise.all([getChapterCleanConfig(),listEnabledAIConfigs()]);Object.assign(config,cfg.data||{});aiOptions.value=options.data||[];configVisible.value=true};const saveConfig=async()=>{config.aiConfigId=assertLongId(config.aiConfigId);await saveChapterCleanConfig({...config});configVisible.value=false;ElMessage.success('配置已保存')};const openReview=async id=>{const res=await getChapterCleanResult(assertLongId(id));review.value=res.data;reviewVisible.value=true};const submitReview=async status=>{await reviewChapterCleanResult(assertLongId(review.value.id),{status,cleanedChapterName:review.value.cleanedChapterName,cleanedText:review.value.cleanedText});reviewVisible.value=false;ElMessage.success('审核完成');load()};const reclean=async id=>{await recleanChapterCleanResult(assertLongId(id));ElMessage.success('已重置');load()};const taskLabel=v=>({running:'执行中',completed:'已完成',stopped:'已停止',failed:'失败'})[v]||v;const taskType=v=>({running:'warning',completed:'success',stopped:'info',failed:'danger'})[v]||'info';load()
</script>
<style scoped>.clean-toolbar{display:flex;align-items:center;justify-content:space-between}.clean-toolbar :deep(.el-tabs__header){margin:0}.config-grid,.review-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 16px}.review-grid{margin-top:16px}@media(max-width:720px){.config-grid,.review-grid{grid-template-columns:1fr}}</style>
