<template><div class="gva-form-box"><div class="head"><div><h2>论坛板块</h2><p>维护来源下的采集板块与自动跟进策略。</p></div><el-button type="primary" :icon="Plus" @click="openCreate">新增板块</el-button></div><div class="toolbar"><el-input v-model="keyword" clearable placeholder="板块名称或来源" @keyup.enter="load"/><el-input v-model="sourceId" clearable placeholder="来源 ID" inputmode="numeric"/><el-button :icon="Search" @click="load">查询</el-button></div><el-table v-loading="loading" :data="rows" border><el-table-column label="板块 ID" width="170"><template #default="{row}"><code>{{row.id}}</code></template></el-table-column><el-table-column prop="sourceName" label="来源" width="140"/><el-table-column prop="boardName" label="板块名称" width="150"/><el-table-column prop="boardUrl" label="地址" min-width="260" show-overflow-tooltip/><el-table-column prop="followIntervalMinutes" label="跟进间隔（分）" width="130"/><el-table-column prop="followImportLimit" label="单次上限" width="100"/><el-table-column label="状态" width="90"><template #default="{row}">{{row.enabled?'启用':'停用'}}</template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @size-change="load" @current-change="load"/></div><el-dialog v-model="dialog" :title="editing?'编辑论坛板块':'新增论坛板块'" width="600px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-form-item label="来源 ID" prop="sourceId"><el-input v-model="form.sourceId" inputmode="numeric"/></el-form-item><el-form-item label="板块名称" prop="boardName"><el-input v-model="form.boardName" maxlength="100"/></el-form-item><el-form-item label="板块地址" prop="boardUrl"><el-input v-model="form.boardUrl" maxlength="500"/></el-form-item><el-form-item label="分页地址模板"><el-input v-model="form.boardUrlTemplate" placeholder="可选，必须包含 {page}" maxlength="500"/></el-form-item><el-form-item label="跟进间隔（分钟）" prop="followIntervalMinutes"><el-input v-model="form.followIntervalMinutes" inputmode="numeric"/></el-form-item><el-form-item label="单次导入上限" prop="followImportLimit"><el-input v-model="form.followImportLimit" inputmode="numeric"/></el-form-item><el-form-item label="排序" prop="sortOrder"><el-input v-model="form.sortOrder" inputmode="numeric"/></el-form-item><el-form-item label="自动跟进"><el-switch v-model="form.autoFollowEnabled"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled"/></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" maxlength="500"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<script setup>
import { reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Search } from '@element-plus/icons-vue'
import { listCrawlBoards, createCrawlBoard, updateCrawlBoard, deleteCrawlBoard } from '@/api/novel/crawlBoards'
defineOptions({ name: 'NovelCrawlBoards' })
const rows=ref([]),total=ref(0),page=ref(1),pageSize=ref(20),keyword=ref(''),sourceId=ref(''),loading=ref(false),dialog=ref(false),editing=ref(false),saving=ref(false),formRef=ref(),boardId=ref('')
const form=reactive({sourceId:'',boardName:'',boardUrl:'',boardUrlTemplate:'',autoFollowEnabled:false,followIntervalMinutes:'60',followImportLimit:'20',enabled:true,sortOrder:'0',remark:''})
const rules={sourceId:[{required:true,pattern:/^[1-9]\d*$/,message:'请输入来源 ID',trigger:'blur'}],boardName:[{required:true,message:'请输入板块名称',trigger:'blur'}],boardUrl:[{required:true,type:'url',message:'请输入合法 URL',trigger:'blur'}],followIntervalMinutes:[{required:true,pattern:/^\d+$/,message:'请输入正整数',trigger:'blur'}],followImportLimit:[{required:true,pattern:/^\d+$/,message:'请输入正整数',trigger:'blur'}],sortOrder:[{required:true,pattern:/^\d+$/,message:'请输入非负整数',trigger:'blur'}]}
const load=async()=>{loading.value=true;try{const r=await listCrawlBoards({keyword:keyword.value,sourceId:sourceId.value,page:page.value,pageSize:pageSize.value});rows.value=r.data?.list||[];total.value=r.data?.total||0}finally{loading.value=false}}
const reset=()=>Object.assign(form,{sourceId:'',boardName:'',boardUrl:'',boardUrlTemplate:'',autoFollowEnabled:false,followIntervalMinutes:'60',followImportLimit:'20',enabled:true,sortOrder:'0',remark:''})
const openCreate=()=>{editing.value=false;boardId.value='';reset();dialog.value=true};const openEdit=(r)=>{editing.value=true;boardId.value=r.id;Object.assign(form,{sourceId:r.sourceId,boardName:r.boardName,boardUrl:r.boardUrl,boardUrlTemplate:r.boardUrlTemplate,autoFollowEnabled:r.autoFollowEnabled,followIntervalMinutes:r.followIntervalMinutes,followImportLimit:r.followImportLimit,enabled:r.enabled,sortOrder:r.sortOrder,remark:r.remark});dialog.value=true}
const save=async()=>{if(!(await formRef.value?.validate().catch(()=>false)))return;saving.value=true;try{editing.value?await updateCrawlBoard(boardId.value,{...form}):await createCrawlBoard({...form});ElMessage.success('保存成功');dialog.value=false;load()}finally{saving.value=false}}
const remove=async(r)=>{try{await ElMessageBox.confirm(`确定删除板块“${r.boardName}”吗？`,'删除确认',{type:'warning'});await deleteCrawlBoard(r.id);ElMessage.success('删除成功');load()}catch{ElMessage.info('已取消删除')}}
load()
</script>
<style scoped>.gva-form-box{padding:20px}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.head h2{margin:0}.head p{color:var(--el-text-color-secondary)}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar .el-input{max-width:280px}.pager{display:flex;justify-content:flex-end;margin-top:16px}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}</style>
