<template>
  <div class="gva-form-box feedback-page"><div class="page-head"><div><h2>读者反馈</h2><p>处理读者提交的问题和建议，已回复内容不可重复覆盖。</p></div><el-button :icon="Refresh" @click="load">刷新</el-button></div><div class="toolbar"><el-input v-model="keyword" clearable placeholder="读者账号或反馈内容" @keyup.enter="load" /><el-select v-model="status" clearable placeholder="状态" @change="load"><el-option label="待处理" value="pending" /><el-option label="已回复" value="replied" /></el-select><el-button :icon="Search" @click="load">查询</el-button></div><el-table v-loading="loading" :data="rows" border><el-table-column label="反馈 ID" min-width="180"><template #default="{ row }"><code>{{row.id}}</code></template></el-table-column><el-table-column prop="readerUsername" label="读者" width="150" /><el-table-column prop="content" label="内容" min-width="320" show-overflow-tooltip /><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="createdAt" label="提交时间" min-width="180" /><el-table-column label="操作" width="120"><template #default="{ row }"><el-button link type="primary" @click="open(row)">{{row.status === 'pending' ? '回复' : '查看'}}</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @size-change="load" @current-change="load" /></div><el-dialog v-model="dialog" title="反馈详情" width="560px"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item label="反馈 ID"><code>{{detail.id}}</code></el-descriptions-item><el-descriptions-item label="读者">{{detail.readerUsername}}（{{detail.readerId}}）</el-descriptions-item><el-descriptions-item label="内容">{{detail.content}}</el-descriptions-item><el-descriptions-item label="已有回复">{{detail.reply || '-'}}</el-descriptions-item></el-descriptions><el-input v-if="detail?.status === 'pending'" v-model="reply" type="textarea" :rows="5" maxlength="5000" show-word-limit placeholder="请输入回复内容" /><template v-if="detail?.status === 'pending'" #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">回复</el-button></template></el-dialog></div>
</template>
<script setup>
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Refresh, Search } from '@element-plus/icons-vue'
import { getReaderFeedback, listReaderFeedback, replyReaderFeedback } from '@/api/reader/feedback'
defineOptions({ name: 'ReaderFeedback' })
const rows=ref([]);const total=ref(0);const page=ref(1);const pageSize=ref(20);const keyword=ref('');const status=ref('');const loading=ref(false);const dialog=ref(false);const detail=ref(null);const reply=ref('');const saving=ref(false)
const load=async()=>{loading.value=true;try{const res=await listReaderFeedback({keyword:keyword.value,status:status.value,page:page.value,pageSize:pageSize.value});rows.value=res.data?.list||[];total.value=res.data?.total||0}finally{loading.value=false}}
const open=async(row)=>{const res=await getReaderFeedback(row.id);detail.value=res.data;reply.value='';dialog.value=true}
const save=async()=>{if(!reply.value.trim())return;saving.value=true;try{await replyReaderFeedback(detail.value.id,reply.value);ElMessage.success('回复成功');dialog.value=false;await load()}finally{saving.value=false}}
load()
</script>
<style scoped>.feedback-page{padding:20px}.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.page-head h2{margin:0}.page-head p{margin:6px 0 0;color:var(--el-text-color-secondary)}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar .el-input{max-width:340px}.pager{display:flex;justify-content:flex-end;margin-top:16px}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}</style>
