<template>
  <div class="gva-form-box orders-page">
    <div class="page-head"><div><h2>消费订单</h2><p>核对购买订单，并通过待确认订单执行模拟充值。</p></div><div class="head-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button type="primary" :icon="Plus" @click="openRecharge">模拟充值</el-button></div></div>
    <div class="toolbar"><el-input v-model="keyword" clearable placeholder="订单号或读者账号" @keyup.enter="load" /><el-select v-model="orderType" clearable placeholder="订单类型" @change="load"><el-option label="会员" value="membership" /><el-option label="章节" value="chapter" /><el-option label="整书" value="book" /><el-option label="模拟充值" value="mock_recharge" /></el-select><el-select v-model="status" clearable placeholder="订单状态" @change="load"><el-option label="待确认" value="pending" /><el-option label="已支付" value="paid" /><el-option label="失败" value="failed" /><el-option label="已退款" value="refunded" /></el-select><el-button :icon="Search" @click="load">查询</el-button></div>
    <el-table v-loading="loading" :data="rows" border><el-table-column label="订单 ID" min-width="180"><template #default="{ row }"><code>{{ row.id }}</code></template></el-table-column><el-table-column prop="orderNo" label="订单号" min-width="180" /><el-table-column prop="readerUsername" label="读者" min-width="140" /><el-table-column prop="orderType" label="类型" width="110" /><el-table-column prop="productName" label="商品" min-width="180" /><el-table-column label="价格/扣款" min-width="150"><template #default="{ row }"><code>{{ row.priceCoin }}</code> / <code>{{ row.rechargeCoinAmount }}</code> + <code>{{ row.bonusCoinAmount }}</code></template></el-table-column><el-table-column prop="status" label="状态" width="100" /><el-table-column label="操作" width="150" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="show(row)">查看</el-button><el-button v-if="row.orderType === 'mock_recharge' && row.status === 'pending'" link type="success" :icon="CircleCheck" @click="confirmRecharge(row)">确认</el-button></template></el-table-column></el-table>
    <div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @size-change="load" @current-change="load" /></div>
    <el-drawer v-model="drawer" title="消费订单详情" size="540px"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item label="订单 ID"><code>{{ detail.id }}</code></el-descriptions-item><el-descriptions-item label="订单号">{{ detail.orderNo }}</el-descriptions-item><el-descriptions-item label="读者">{{ detail.readerUsername }}（{{ detail.readerId }}）</el-descriptions-item><el-descriptions-item label="商品">{{ detail.productName }}（{{ detail.productType }}）</el-descriptions-item><el-descriptions-item label="目标 ID"><code>{{ detail.targetId || '-' }}</code></el-descriptions-item><el-descriptions-item label="价格"><code>{{ detail.priceCoin }}</code></el-descriptions-item><el-descriptions-item label="扣款拆分">充值币 <code>{{ detail.rechargeCoinAmount }}</code>，奖励币 <code>{{ detail.bonusCoinAmount }}</code></el-descriptions-item><el-descriptions-item label="状态">{{ detail.status }}</el-descriptions-item><el-descriptions-item label="支付时间">{{ detail.paidAt || '-' }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ detail.createdAt }}</el-descriptions-item></el-descriptions></el-drawer>
    <el-dialog v-model="rechargeDialog" title="创建模拟充值订单" width="460px"><el-form ref="rechargeFormRef" :model="rechargeForm" :rules="rechargeRules" label-position="top"><el-form-item label="读者 ID" prop="readerId"><el-input v-model="rechargeForm.readerId" inputmode="numeric" maxlength="20" /></el-form-item><el-form-item label="充值币数量" prop="rechargeCoinAmount"><el-input v-model="rechargeForm.rechargeCoinAmount" inputmode="numeric" maxlength="19" /></el-form-item><el-form-item label="备注" prop="remark"><el-input v-model="rechargeForm.remark" type="textarea" maxlength="255" show-word-limit /></el-form-item></el-form><template #footer><el-button @click="rechargeDialog=false">取消</el-button><el-button type="primary" :loading="rechargeSaving" @click="saveRecharge">创建待确认订单</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import { reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { CircleCheck, Plus, Refresh, Search } from '@element-plus/icons-vue'
import { confirmMockRecharge, createMockRecharge, getOrder, listOrders } from '@/api/reader/orders'
defineOptions({ name: 'ReaderOrders' })
const rows = ref([]); const total = ref(0); const page = ref(1); const pageSize = ref(20); const keyword = ref(''); const orderType = ref(''); const status = ref(''); const loading = ref(false); const drawer = ref(false); const detail = ref(null)
const rechargeDialog = ref(false); const rechargeSaving = ref(false); const rechargeFormRef = ref(); const rechargeForm = reactive({ readerId: '', rechargeCoinAmount: '', remark: '', requestId: '' })
const positiveInteger = (_rule, value, callback) => /^[1-9]\d*$/.test(value || '') ? callback() : callback(new Error('请输入正整数字符串'))
const rechargeRules = { readerId: [{ required: true, validator: positiveInteger, trigger: 'blur' }], rechargeCoinAmount: [{ required: true, validator: positiveInteger, trigger: 'blur' }] }
const load = async () => { loading.value = true; try { const res = await listOrders({ keyword: keyword.value, orderType: orderType.value, status: status.value, page: page.value, pageSize: pageSize.value }); rows.value = res.data?.list || []; total.value = res.data?.total || 0 } finally { loading.value = false } }
const show = async (row) => { try { const res = await getOrder(row.id); detail.value = res.data; drawer.value = true } catch { ElMessage.error('加载订单失败') } }
const openRecharge = () => { Object.assign(rechargeForm, { readerId: '', rechargeCoinAmount: '', remark: '', requestId: crypto.randomUUID() }); rechargeDialog.value = true }
const saveRecharge = async () => { if (!(await rechargeFormRef.value?.validate().catch(() => false))) return; rechargeSaving.value = true; try { await createMockRecharge({ ...rechargeForm }); ElMessage.success('待确认订单已创建'); rechargeDialog.value = false; await load() } finally { rechargeSaving.value = false } }
const confirmRecharge = async (row) => { await ElMessageBox.confirm(`确认向读者 ${row.readerUsername} 充值 ${row.rechargeCoinAmount} 充值币？`, '确认模拟充值', { type: 'warning' }); await confirmMockRecharge(row.id); ElMessage.success('模拟充值已入账'); await load() }
load()
</script>
<style scoped>.orders-page{padding:20px}.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.page-head h2{margin:0}.page-head p{margin:6px 0 0;color:var(--el-text-color-secondary)}.head-actions,.toolbar{display:flex;gap:10px}.toolbar{margin-bottom:14px}.toolbar .el-input{max-width:280px}.pager{display:flex;justify-content:flex-end;margin-top:16px}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}</style>
