<template>
  <div class="gva-form-box orders-page">
    <div class="page-head"><div><h2>消费订单</h2><p>只读核对读者购买订单、扣款拆分和权益订单状态。</p></div><el-button :icon="Refresh" @click="load">刷新</el-button></div>
    <div class="toolbar"><el-input v-model="keyword" clearable placeholder="订单号或读者账号" @keyup.enter="load" /><el-select v-model="orderType" clearable placeholder="订单类型" @change="load"><el-option label="会员" value="membership" /><el-option label="章节" value="chapter" /><el-option label="整书" value="book" /></el-select><el-select v-model="status" clearable placeholder="订单状态" @change="load"><el-option label="已支付" value="paid" /><el-option label="失败" value="failed" /><el-option label="已退款" value="refunded" /></el-select><el-button :icon="Search" @click="load">查询</el-button></div>
    <el-table v-loading="loading" :data="rows" border><el-table-column label="订单 ID" min-width="180"><template #default="{ row }"><code>{{ row.id }}</code></template></el-table-column><el-table-column prop="orderNo" label="订单号" min-width="180" /><el-table-column prop="readerUsername" label="读者" min-width="140" /><el-table-column prop="orderType" label="类型" width="110" /><el-table-column prop="productName" label="商品" min-width="180" /><el-table-column label="价格/扣款" min-width="150"><template #default="{ row }"><code>{{ row.priceCoin }}</code> / <code>{{ row.rechargeCoinAmount }}</code> + <code>{{ row.bonusCoinAmount }}</code></template></el-table-column><el-table-column prop="status" label="状态" width="100" /><el-table-column label="详情" width="90"><template #default="{ row }"><el-button link type="primary" @click="show(row)">查看</el-button></template></el-table-column></el-table>
    <div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @size-change="load" @current-change="load" /></div>
    <el-drawer v-model="drawer" title="消费订单详情" size="540px"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item label="订单 ID"><code>{{ detail.id }}</code></el-descriptions-item><el-descriptions-item label="订单号">{{ detail.orderNo }}</el-descriptions-item><el-descriptions-item label="读者">{{ detail.readerUsername }}（{{ detail.readerId }}）</el-descriptions-item><el-descriptions-item label="商品">{{ detail.productName }}（{{ detail.productType }}）</el-descriptions-item><el-descriptions-item label="目标 ID"><code>{{ detail.targetId || '-' }}</code></el-descriptions-item><el-descriptions-item label="价格"><code>{{ detail.priceCoin }}</code></el-descriptions-item><el-descriptions-item label="扣款拆分">充值币 <code>{{ detail.rechargeCoinAmount }}</code>，奖励币 <code>{{ detail.bonusCoinAmount }}</code></el-descriptions-item><el-descriptions-item label="状态">{{ detail.status }}</el-descriptions-item><el-descriptions-item label="支付时间">{{ detail.paidAt || '-' }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ detail.createdAt }}</el-descriptions-item></el-descriptions></el-drawer>
  </div>
</template>
<script setup>
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Refresh, Search } from '@element-plus/icons-vue'
import { getOrder, listOrders } from '@/api/reader/orders'
defineOptions({ name: 'ReaderOrders' })
const rows = ref([]); const total = ref(0); const page = ref(1); const pageSize = ref(20); const keyword = ref(''); const orderType = ref(''); const status = ref(''); const loading = ref(false); const drawer = ref(false); const detail = ref(null)
const load = async () => { loading.value = true; try { const res = await listOrders({ keyword: keyword.value, orderType: orderType.value, status: status.value, page: page.value, pageSize: pageSize.value }); rows.value = res.data?.list || []; total.value = res.data?.total || 0 } finally { loading.value = false } }
const show = async (row) => { try { const res = await getOrder(row.id); detail.value = res.data; drawer.value = true } catch { ElMessage.error('加载订单失败') } }
load()
</script>
<style scoped>.orders-page{padding:20px}.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.page-head h2{margin:0}.page-head p{margin:6px 0 0;color:var(--el-text-color-secondary)}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar .el-input{max-width:280px}.pager{display:flex;justify-content:flex-end;margin-top:16px}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}</style>
