-- +goose Up
-- +goose StatementBegin
CREATE TABLE platform_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module varchar(64) NOT NULL,
    job_type varchar(64) NOT NULL,
    idempotency_key varchar(191) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'pending',
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    result jsonb,
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    available_at timestamptz NOT NULL DEFAULT now(),
    lease_owner varchar(128),
    lease_expires_at timestamptz,
    last_error_code varchar(64),
    last_error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    CONSTRAINT platform_jobs_status_check CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
    CONSTRAINT platform_jobs_attempt_count_check CHECK (attempt_count >= 0),
    CONSTRAINT platform_jobs_max_attempts_check CHECK (max_attempts > 0),
    CONSTRAINT platform_jobs_idempotency_unique UNIQUE (module, job_type, idempotency_key)
);

CREATE INDEX platform_jobs_claim_idx
    ON platform_jobs (status, available_at, id)
    WHERE status IN ('pending', 'running');

CREATE TABLE platform_job_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES platform_jobs(id),
    attempt_number integer NOT NULL,
    worker_id varchar(128) NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    outcome varchar(24),
    error_code varchar(64),
    error_message text,
    CONSTRAINT platform_job_attempt_number_check CHECK (attempt_number > 0),
    CONSTRAINT platform_job_attempt_outcome_check CHECK (outcome IS NULL OR outcome IN ('succeeded', 'retry', 'failed', 'cancelled')),
    CONSTRAINT platform_job_attempt_unique UNIQUE (job_id, attempt_number)
);

CREATE TABLE migration_checkpoints (
    migration_name varchar(128) NOT NULL,
    stage varchar(128) NOT NULL,
    cursor_value varchar(191),
    processed_count bigint NOT NULL DEFAULT 0,
    error_count bigint NOT NULL DEFAULT 0,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_name, stage),
    CONSTRAINT migration_checkpoints_processed_check CHECK (processed_count >= 0),
    CONSTRAINT migration_checkpoints_error_check CHECK (error_count >= 0)
);

CREATE TABLE migration_errors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_name varchar(128) NOT NULL,
    stage varchar(128) NOT NULL,
    source_table varchar(128),
    source_id varchar(191),
    error_code varchar(64) NOT NULL,
    error_message text NOT NULL,
    retryable boolean NOT NULL DEFAULT false,
    resolved_at timestamptz,
    resolution_note text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX migration_errors_open_idx
    ON migration_errors (migration_name, stage, id)
    WHERE resolved_at IS NULL;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$
BEGIN
    RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration';
END
$$;
-- +goose StatementEnd
