-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL,
    name varchar(100) NOT NULL,
    kind varchar(16) NOT NULL,
    work_direction varchar(32),
    sort integer NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    source varchar(32) NOT NULL DEFAULT 'native',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT novel_categories_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT novel_categories_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT novel_categories_kind_check CHECK (kind IN ('primary', 'sub')),
    CONSTRAINT novel_categories_sort_check CHECK (sort >= 0),
    CONSTRAINT novel_categories_source_check CHECK (source IN ('native', 'legacy_dict', 'legacy_category', 'legacy_relation'))
);

CREATE UNIQUE INDEX novel_categories_kind_code_unique
    ON novel_categories (kind, code)
    WHERE deleted_at IS NULL;
CREATE INDEX novel_categories_list_idx
    ON novel_categories (kind, enabled DESC, sort, id)
    WHERE deleted_at IS NULL;

CREATE TABLE novel_authors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pen_name varchar(100) NOT NULL,
    normalized_name varchar(100) NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'active',
    work_direction varchar(32),
    source varchar(32) NOT NULL DEFAULT 'native',
    legacy_author_id bigint,
    legacy_book_author_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT novel_authors_pen_name_not_blank CHECK (btrim(pen_name) <> ''),
    CONSTRAINT novel_authors_normalized_name_not_blank CHECK (btrim(normalized_name) <> ''),
    CONSTRAINT novel_authors_status_check CHECK (status IN ('pending', 'active', 'blocked')),
    CONSTRAINT novel_authors_source_check CHECK (source IN ('native', 'legacy_author', 'legacy_book_author', 'legacy_book')),
    CONSTRAINT novel_authors_legacy_author_unique UNIQUE (legacy_author_id),
    CONSTRAINT novel_authors_legacy_book_author_unique UNIQUE (legacy_book_author_id)
);

CREATE INDEX novel_authors_name_idx
    ON novel_authors (normalized_name, id)
    WHERE deleted_at IS NULL;
CREATE INDEX novel_authors_status_idx
    ON novel_authors (status, id)
    WHERE deleted_at IS NULL;

INSERT INTO sys_base_menus
    (id, created_at, updated_at, menu_level, parent_id, path, name, hidden, component, sort,
     active_name, keep_alive, default_menu, title, icon, close_tab, transition_type)
VALUES
    (1000, now(), now(), 0, 0, 'novel', 'Novel', false, 'view/routerHolder.vue', 20,
     '', false, false, '小说管理', 'reading', false, ''),
    (1001, now(), now(), 1, 1000, 'metadata', 'NovelMetadata', false, 'view/novel/metadata/index.vue', 1,
     '', true, false, '分类管理', 'collection-tag', false, ''),
    (1002, now(), now(), 1, 1000, 'authors', 'NovelAuthors', false, 'view/novel/authors/index.vue', 2,
     '', true, false, '作者管理', 'user', false, '')
ON CONFLICT DO NOTHING;

INSERT INTO sys_authority_menus (sys_base_menu_id, sys_authority_authority_id)
VALUES (1000, 888), (1001, 888), (1002, 888)
ON CONFLICT DO NOTHING;

INSERT INTO sys_apis (id, created_at, updated_at, path, description, api_group, method)
VALUES
    (1000, now(), now(), '/novel/categories', '查询小说分类', '小说元数据', 'GET'),
    (1001, now(), now(), '/novel/categories', '新增小说分类', '小说元数据', 'POST'),
    (1002, now(), now(), '/novel/categories/:id', '修改小说分类', '小说元数据', 'PUT'),
    (1003, now(), now(), '/novel/categories/:id', '删除小说分类', '小说元数据', 'DELETE'),
    (1004, now(), now(), '/novel/authors', '查询小说作者', '小说元数据', 'GET'),
    (1005, now(), now(), '/novel/authors', '新增小说作者', '小说元数据', 'POST'),
    (1006, now(), now(), '/novel/authors/:id', '修改小说作者', '小说元数据', 'PUT'),
    (1007, now(), now(), '/novel/authors/:id', '删除小说作者', '小说元数据', 'DELETE')
ON CONFLICT DO NOTHING;

INSERT INTO casbin_rule (ptype, v0, v1, v2, v3, v4, v5)
VALUES
    ('p', '888', '/novel/categories', 'GET', '', '', ''),
    ('p', '888', '/novel/categories', 'POST', '', '', ''),
    ('p', '888', '/novel/categories/:id', 'PUT', '', '', ''),
    ('p', '888', '/novel/categories/:id', 'DELETE', '', '', ''),
    ('p', '888', '/novel/authors', 'GET', '', '', ''),
    ('p', '888', '/novel/authors', 'POST', '', '', ''),
    ('p', '888', '/novel/authors/:id', 'PUT', '', '', ''),
    ('p', '888', '/novel/authors/:id', 'DELETE', '', '', '')
ON CONFLICT DO NOTHING;

SELECT setval('sys_base_menus_id_seq', GREATEST((SELECT max(id) FROM sys_base_menus), 1002), true);
SELECT setval('sys_apis_id_seq', GREATEST((SELECT max(id) FROM sys_apis), 1007), true);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$
BEGIN
    RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration';
END
$$;
-- +goose StatementEnd
