-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_books (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_direction varchar(32),
    primary_category_id bigint NOT NULL REFERENCES novel_categories(id),
    category_code varchar(64) NOT NULL,
    category_name varchar(100) NOT NULL,
    legacy_cover_url varchar(500) NOT NULL DEFAULT '',
    book_name varchar(100) NOT NULL,
    author_id bigint NOT NULL REFERENCES novel_authors(id),
    author_name varchar(100) NOT NULL,
    description varchar(2000) NOT NULL DEFAULT '',
    score numeric(5,2) NOT NULL DEFAULT 0,
    book_status varchar(16) NOT NULL DEFAULT 'serializing',
    publish_status varchar(16) NOT NULL DEFAULT 'draft',
    source_type varchar(32) NOT NULL DEFAULT 'manual',
    featured boolean NOT NULL DEFAULT false,
    featured_sort integer NOT NULL DEFAULT 0,
    featured_note varchar(255) NOT NULL DEFAULT '',
    visit_count bigint NOT NULL DEFAULT 0,
    like_count integer NOT NULL DEFAULT 0,
    word_count integer NOT NULL DEFAULT 0,
    comment_count integer NOT NULL DEFAULT 0,
    yesterday_buy integer NOT NULL DEFAULT 0,
    last_chapter_id bigint,
    last_chapter_name varchar(255),
    last_chapter_updated_at timestamptz,
    charge_mode varchar(32) NOT NULL DEFAULT 'word_charge',
    fixed_price_coin bigint,
    legacy_crawl_source_id bigint,
    legacy_crawl_book_id varchar(128),
    legacy_crawl_last_at timestamptz,
    legacy_crawl_stopped boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT novel_books_name_not_blank CHECK (btrim(book_name) <> ''),
    CONSTRAINT novel_books_author_name_not_blank CHECK (btrim(author_name) <> ''),
    CONSTRAINT novel_books_category_not_blank CHECK (btrim(category_code) <> '' AND btrim(category_name) <> ''),
    CONSTRAINT novel_books_score_check CHECK (score >= 0 AND score <= 10),
    CONSTRAINT novel_books_status_check CHECK (book_status IN ('serializing','completed')),
    CONSTRAINT novel_books_publish_check CHECK (publish_status IN ('draft','published','deprecated')),
    CONSTRAINT novel_books_source_check CHECK (source_type IN ('manual','legacy','txt_import','forum_crawl')),
    CONSTRAINT novel_books_counts_check CHECK (visit_count >= 0 AND like_count >= 0 AND word_count >= 0 AND comment_count >= 0 AND yesterday_buy >= 0),
    CONSTRAINT novel_books_featured_sort_check CHECK (featured_sort >= 0),
    CONSTRAINT novel_books_charge_check CHECK (charge_mode IN ('word_charge','membership_only','login_free','fixed_price')),
    CONSTRAINT novel_books_fixed_price_check CHECK ((charge_mode = 'fixed_price' AND fixed_price_coin > 0) OR (charge_mode <> 'fixed_price' AND fixed_price_coin IS NULL))
);

CREATE UNIQUE INDEX novel_books_name_author_unique
    ON novel_books (book_name, author_name) WHERE deleted_at IS NULL;
CREATE INDEX novel_books_admin_list_idx ON novel_books (publish_status, updated_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX novel_books_reader_list_idx ON novel_books (featured DESC, featured_sort, id DESC) WHERE deleted_at IS NULL AND publish_status='published';
CREATE INDEX novel_books_author_idx ON novel_books (author_id, id) WHERE deleted_at IS NULL;
CREATE INDEX novel_books_category_idx ON novel_books (primary_category_id, id) WHERE deleted_at IS NULL;

CREATE TABLE novel_book_sub_categories (
    book_id bigint NOT NULL REFERENCES novel_books(id),
    category_id bigint NOT NULL REFERENCES novel_categories(id),
    category_code varchar(64) NOT NULL,
    category_name varchar(100) NOT NULL,
    sort integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (book_id, category_id),
    CONSTRAINT novel_book_sub_categories_sort_check CHECK (sort >= 0),
    CONSTRAINT novel_book_sub_categories_code_unique UNIQUE (book_id, category_code)
);

CREATE TABLE novel_book_tags (
    book_id bigint NOT NULL REFERENCES novel_books(id),
    tag varchar(64) NOT NULL,
    sort integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (book_id, tag),
    CONSTRAINT novel_book_tags_not_blank CHECK (btrim(tag) <> ''),
    CONSTRAINT novel_book_tags_sort_check CHECK (sort >= 0)
);

INSERT INTO sys_base_menus
    (id, created_at, updated_at, menu_level, parent_id, path, name, hidden, component, sort,
     active_name, keep_alive, default_menu, title, icon, close_tab, transition_type)
VALUES (1003, now(), now(), 1, 1000, 'books', 'NovelBooks', false, 'view/novel/books/index.vue', 3,
    '', true, false, '书籍管理', 'reading', false, '')
ON CONFLICT DO NOTHING;

INSERT INTO sys_authority_menus (sys_base_menu_id, sys_authority_authority_id)
VALUES (1003, 888) ON CONFLICT DO NOTHING;

INSERT INTO sys_apis (id, created_at, updated_at, path, description, api_group, method)
VALUES
    (1008, now(), now(), '/novel/books', '查询小说书籍', '小说书籍', 'GET'),
    (1009, now(), now(), '/novel/books/:id', '查询小说书籍详情', '小说书籍', 'GET'),
    (1010, now(), now(), '/novel/books', '新增小说书籍', '小说书籍', 'POST'),
    (1011, now(), now(), '/novel/books/:id', '修改小说书籍', '小说书籍', 'PUT'),
    (1012, now(), now(), '/novel/books/:id', '删除小说书籍', '小说书籍', 'DELETE')
ON CONFLICT DO NOTHING;

INSERT INTO casbin_rule (ptype, v0, v1, v2, v3, v4, v5)
VALUES
    ('p','888','/novel/books','GET','','',''),
    ('p','888','/novel/books/:id','GET','','',''),
    ('p','888','/novel/books','POST','','',''),
    ('p','888','/novel/books/:id','PUT','','',''),
    ('p','888','/novel/books/:id','DELETE','','','')
ON CONFLICT DO NOTHING;

SELECT setval('sys_base_menus_id_seq', GREATEST((SELECT max(id) FROM sys_base_menus), 1003), true);
SELECT setval('sys_apis_id_seq', GREATEST((SELECT max(id) FROM sys_apis), 1012), true);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
