-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_objects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_kind varchar(32) NOT NULL,
    book_id bigint NOT NULL,
    owner_id bigint NOT NULL,
    version integer NOT NULL,
    object_key varchar(512) NOT NULL,
    sha256 char(64),
    byte_size bigint,
    content_type varchar(191) NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'uploading',
    source varchar(32) NOT NULL DEFAULT 'native',
    error_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(),
    verified_at timestamptz,
    activated_at timestamptz,
    orphaned_at timestamptz,
    deleted_at timestamptz,
    CONSTRAINT novel_objects_kind_check CHECK (object_kind IN ('chapter_content', 'book_cover')),
    CONSTRAINT novel_objects_ids_check CHECK (book_id > 0 AND owner_id > 0),
    CONSTRAINT novel_objects_version_check CHECK (version > 0),
    CONSTRAINT novel_objects_key_not_blank CHECK (btrim(object_key) <> ''),
    CONSTRAINT novel_objects_sha256_check CHECK (sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT novel_objects_byte_size_check CHECK (byte_size IS NULL OR byte_size >= 0),
    CONSTRAINT novel_objects_state_check CHECK (state IN ('uploading', 'verified', 'active', 'orphaned', 'failed', 'deleting', 'deleted')),
    CONSTRAINT novel_objects_source_check CHECK (source IN ('native', 'legacy', 'import')),
    CONSTRAINT novel_objects_target_version_unique UNIQUE (object_kind, book_id, owner_id, version),
    CONSTRAINT novel_objects_key_unique UNIQUE (object_key)
);

CREATE INDEX novel_objects_gc_idx
    ON novel_objects (state, COALESCE(orphaned_at, created_at), id)
    WHERE state IN ('uploading', 'orphaned', 'failed', 'deleting');

CREATE TABLE novel_object_references (
    object_kind varchar(32) NOT NULL,
    book_id bigint NOT NULL,
    owner_id bigint NOT NULL,
    object_id bigint NOT NULL UNIQUE REFERENCES novel_objects(id),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (object_kind, book_id, owner_id),
    CONSTRAINT novel_object_references_kind_check CHECK (object_kind IN ('chapter_content', 'book_cover')),
    CONSTRAINT novel_object_references_ids_check CHECK (book_id > 0 AND owner_id > 0)
);

CREATE TABLE novel_object_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id bigint NOT NULL REFERENCES novel_objects(id),
    event_type varchar(32) NOT NULL,
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_object_events_type_check CHECK (event_type IN ('reserved', 'verified', 'activated', 'orphaned', 'failed', 'delete_started', 'delete_failed', 'deleted'))
);

CREATE INDEX novel_object_events_object_idx ON novel_object_events (object_id, id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$
BEGIN
    RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration';
END
$$;
-- +goose StatementEnd
