-- +goose Up
-- +goose StatementBegin
CREATE TABLE reader_wallets (
    reader_id bigint PRIMARY KEY REFERENCES reader_accounts(id),
    recharge_coin_balance bigint NOT NULL DEFAULT 0,
    bonus_coin_balance bigint NOT NULL DEFAULT 0,
    total_recharge_coin_income bigint NOT NULL DEFAULT 0,
    total_bonus_coin_income bigint NOT NULL DEFAULT 0,
    total_recharge_coin_expense bigint NOT NULL DEFAULT 0,
    total_bonus_coin_expense bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_wallets_balance_check CHECK (recharge_coin_balance >= 0 AND bonus_coin_balance >= 0),
    CONSTRAINT reader_wallets_totals_check CHECK (total_recharge_coin_income >= 0 AND total_bonus_coin_income >= 0 AND total_recharge_coin_expense >= 0 AND total_bonus_coin_expense >= 0)
);

CREATE TABLE reader_wallet_ledgers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    ledger_no varchar(64) NOT NULL,
    biz_type varchar(32) NOT NULL,
    biz_id varchar(128),
    order_no varchar(64),
    direction varchar(16) NOT NULL,
    coin_type varchar(16) NOT NULL,
    amount bigint NOT NULL,
    balance_before bigint NOT NULL,
    balance_after bigint NOT NULL,
    remark varchar(255),
    idempotency_key varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_wallet_ledgers_no_unique UNIQUE (ledger_no),
    CONSTRAINT reader_wallet_ledgers_direction_check CHECK (direction IN ('income', 'expense')),
    CONSTRAINT reader_wallet_ledgers_coin_check CHECK (coin_type IN ('recharge', 'bonus')),
    CONSTRAINT reader_wallet_ledgers_amount_check CHECK (amount > 0),
    CONSTRAINT reader_wallet_ledgers_balance_check CHECK (balance_before >= 0 AND balance_after >= 0)
);
CREATE UNIQUE INDEX reader_wallet_ledgers_idempotency_unique ON reader_wallet_ledgers (reader_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX reader_wallet_ledgers_reader_time_idx ON reader_wallet_ledgers (reader_id, created_at DESC, id DESC);
CREATE INDEX reader_wallet_ledgers_reader_coin_idx ON reader_wallet_ledgers (reader_id, coin_type, created_at DESC, id DESC);

CREATE OR REPLACE FUNCTION moonbook_wallet_ledger_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'reader wallet ledgers are immutable';
END;
$$;
CREATE TRIGGER reader_wallet_ledgers_immutable_update BEFORE UPDATE OR DELETE ON reader_wallet_ledgers FOR EACH ROW EXECUTE FUNCTION moonbook_wallet_ledger_immutable();
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
