-- +goose Up
-- +goose StatementBegin
CREATE SEQUENCE IF NOT EXISTS commerce_entitlements_id_seq;
SELECT setval('commerce_entitlements_id_seq', GREATEST(COALESCE((SELECT max(id) FROM commerce_entitlements),0),1), true);
ALTER TABLE commerce_entitlements ALTER COLUMN id SET DEFAULT nextval('commerce_entitlements_id_seq');
CREATE SEQUENCE IF NOT EXISTS commerce_membership_grants_id_seq;
SELECT setval('commerce_membership_grants_id_seq', GREATEST(COALESCE((SELECT max(id) FROM commerce_membership_grants),0),1), true);
ALTER TABLE commerce_membership_grants ALTER COLUMN id SET DEFAULT nextval('commerce_membership_grants_id_seq');

CREATE TABLE reader_purchase_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no varchar(64) NOT NULL UNIQUE,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    order_type varchar(24) NOT NULL,
    product_id bigint REFERENCES commerce_products(id),
    product_type varchar(20) NOT NULL,
    target_id bigint,
    book_id_snapshot bigint,
    product_name_snapshot varchar(100) NOT NULL DEFAULT '',
    price_coin_snapshot bigint NOT NULL,
    chapter_word_count_snapshot integer,
    pricing_word_unit_snapshot integer,
    pricing_coin_unit_snapshot bigint,
    recharge_coin_amount bigint NOT NULL DEFAULT 0,
    bonus_coin_amount bigint NOT NULL DEFAULT 0,
    status varchar(16) NOT NULL DEFAULT 'paid',
    idempotency_key varchar(160) NOT NULL,
    remark varchar(255),
    paid_time timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_purchase_orders_idempotency_unique UNIQUE (reader_id,idempotency_key),
    CONSTRAINT reader_purchase_orders_type_check CHECK (order_type IN ('membership','chapter','book')),
    CONSTRAINT reader_purchase_orders_status_check CHECK (status IN ('paid','failed','refunded')),
    CONSTRAINT reader_purchase_orders_price_check CHECK (price_coin_snapshot >= 0 AND recharge_coin_amount >= 0 AND bonus_coin_amount >= 0)
);
CREATE INDEX reader_purchase_orders_reader_time_idx ON reader_purchase_orders (reader_id,created_at DESC,id DESC);
CREATE INDEX reader_purchase_orders_target_idx ON reader_purchase_orders (product_type,target_id,status);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
