-- +goose Up
-- +goose StatementBegin
CREATE TABLE reader_checkin_reward_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_type varchar(16) NOT NULL,
    continuous_days integer,
    reward_mode varchar(16) NOT NULL,
    fixed_coin bigint,
    min_coin bigint,
    max_coin bigint,
    status varchar(16) NOT NULL DEFAULT 'disabled',
    sort_order integer NOT NULL DEFAULT 0,
    remark varchar(255) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_checkin_rules_type_check CHECK (rule_type IN ('daily','continuous')),
    CONSTRAINT reader_checkin_rules_days_check CHECK ((rule_type='daily' AND continuous_days IS NULL) OR (rule_type='continuous' AND continuous_days > 0)),
    CONSTRAINT reader_checkin_rules_mode_check CHECK (reward_mode IN ('fixed','random')),
    CONSTRAINT reader_checkin_rules_reward_check CHECK ((reward_mode='fixed' AND fixed_coin > 0 AND min_coin IS NULL AND max_coin IS NULL) OR (reward_mode='random' AND fixed_coin IS NULL AND min_coin > 0 AND max_coin >= min_coin)),
    CONSTRAINT reader_checkin_rules_status_check CHECK (status IN ('enabled','disabled'))
);
CREATE UNIQUE INDEX reader_checkin_rules_daily_enabled_unique ON reader_checkin_reward_rules ((rule_type)) WHERE rule_type='daily' AND status='enabled';
CREATE UNIQUE INDEX reader_checkin_rules_continuous_enabled_unique ON reader_checkin_reward_rules (continuous_days) WHERE rule_type='continuous' AND status='enabled';
CREATE INDEX reader_checkin_rules_lookup_idx ON reader_checkin_reward_rules (rule_type,status,continuous_days,sort_order,id);
INSERT INTO reader_checkin_reward_rules(id,rule_type,reward_mode,fixed_coin,status,sort_order,remark) VALUES (2607081001,'daily','fixed',10,'enabled',10,'默认每日签到奖励');
INSERT INTO reader_checkin_reward_rules(id,rule_type,continuous_days,reward_mode,fixed_coin,status,sort_order,remark) VALUES (2607081007,'continuous',7,'fixed',50,'enabled',70,'默认连续7天奖励'),(2607081014,'continuous',14,'fixed',100,'enabled',140,'默认连续14天奖励'),(2607081030,'continuous',30,'fixed',300,'enabled',300,'默认连续30天奖励');

CREATE TABLE reader_checkin_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    checkin_date date NOT NULL,
    continuous_days integer NOT NULL,
    base_reward_coin bigint NOT NULL DEFAULT 0,
    milestone_reward_coin bigint NOT NULL DEFAULT 0,
    total_reward_coin bigint NOT NULL DEFAULT 0,
    idempotency_key varchar(128) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_checkin_records_day_unique UNIQUE (reader_id,checkin_date),
    CONSTRAINT reader_checkin_records_key_unique UNIQUE (idempotency_key),
    CONSTRAINT reader_checkin_records_days_check CHECK (continuous_days > 0),
    CONSTRAINT reader_checkin_records_reward_check CHECK (base_reward_coin >= 0 AND milestone_reward_coin >= 0 AND total_reward_coin = base_reward_coin + milestone_reward_coin)
);
CREATE INDEX reader_checkin_records_reader_date_idx ON reader_checkin_records (reader_id,checkin_date DESC);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
