-- +goose Up
-- +goose StatementBegin
CREATE TABLE reader_accounts (
    id bigint PRIMARY KEY,
    username varchar(64) NOT NULL,
    nickname varchar(64) NOT NULL DEFAULT '',
    password_hash varchar(255) NOT NULL,
    password_algorithm varchar(32) NOT NULL DEFAULT 'bcrypt',
    status varchar(16) NOT NULL DEFAULT 'enabled',
    invite_code_id bigint,
    last_login_at timestamptz,
    password_upgraded_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_accounts_username_unique UNIQUE (username),
    CONSTRAINT reader_accounts_algorithm_check CHECK (password_algorithm IN ('bcrypt', 'md5')),
    CONSTRAINT reader_accounts_status_check CHECK (status IN ('enabled', 'disabled', 'deleted')),
    CONSTRAINT reader_accounts_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT reader_accounts_username_not_blank CHECK (btrim(username) <> '')
);

CREATE INDEX reader_accounts_status_idx ON reader_accounts (status, id);

CREATE TABLE reader_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    token_digest char(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz,
    CONSTRAINT reader_sessions_digest_unique UNIQUE (token_digest),
    CONSTRAINT reader_sessions_digest_check CHECK (token_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT reader_sessions_expiry_check CHECK (expires_at > created_at),
    CONSTRAINT reader_sessions_revoked_check CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX reader_sessions_reader_active_idx ON reader_sessions (reader_id, expires_at) WHERE revoked_at IS NULL;

CREATE TABLE reader_invite_codes (
    id bigint PRIMARY KEY,
    code varchar(64) NOT NULL,
    inviter_reader_id bigint REFERENCES reader_accounts(id),
    status varchar(16) NOT NULL DEFAULT 'enabled',
    max_use_count integer,
    used_count integer NOT NULL DEFAULT 0,
    expires_at timestamptz,
    remark varchar(255) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_invite_codes_code_unique UNIQUE (code),
    CONSTRAINT reader_invite_codes_status_check CHECK (status IN ('enabled', 'disabled', 'expired')),
    CONSTRAINT reader_invite_codes_max_check CHECK (max_use_count IS NULL OR max_use_count > 0),
    CONSTRAINT reader_invite_codes_used_check CHECK (used_count >= 0 AND (max_use_count IS NULL OR used_count <= max_use_count)),
    CONSTRAINT reader_invite_codes_code_not_blank CHECK (btrim(code) <> '')
);
CREATE UNIQUE INDEX reader_invite_codes_inviter_unique ON reader_invite_codes (inviter_reader_id) WHERE inviter_reader_id IS NOT NULL;
CREATE INDEX reader_invite_codes_available_idx ON reader_invite_codes (status, expires_at);

CREATE TABLE reader_invite_relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inviter_reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    invitee_reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    invite_code_id bigint NOT NULL REFERENCES reader_invite_codes(id),
    status varchar(16) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_invite_relations_invitee_unique UNIQUE (invitee_reader_id),
    CONSTRAINT reader_invite_relations_status_check CHECK (status IN ('active', 'cancelled')),
    CONSTRAINT reader_invite_relations_distinct_check CHECK (inviter_reader_id <> invitee_reader_id)
);
CREATE INDEX reader_invite_relations_inviter_idx ON reader_invite_relations (inviter_reader_id, created_at);

CREATE TABLE reader_bookshelf_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    book_id bigint NOT NULL REFERENCES novel_books(id),
    last_chapter_id bigint REFERENCES novel_chapters(id),
    last_read_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_bookshelf_entries_reader_book_unique UNIQUE (reader_id, book_id)
);
CREATE INDEX reader_bookshelf_entries_reader_time_idx ON reader_bookshelf_entries (reader_id, last_read_at DESC NULLS LAST);

CREATE TABLE reader_book_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    book_id bigint NOT NULL REFERENCES novel_books(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_book_likes_reader_book_unique UNIQUE (reader_id, book_id)
);
CREATE INDEX reader_book_likes_book_idx ON reader_book_likes (book_id, created_at);

CREATE TABLE reader_reading_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    book_id bigint NOT NULL REFERENCES novel_books(id),
    chapter_id bigint NOT NULL REFERENCES novel_chapters(id),
    chapter_no integer NOT NULL DEFAULT 0,
    position_type varchar(16) NOT NULL DEFAULT 'scroll',
    position_value integer NOT NULL DEFAULT 0,
    progress_percent numeric(5,2) NOT NULL DEFAULT 0,
    last_read_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_reading_history_reader_book_unique UNIQUE (reader_id, book_id),
    CONSTRAINT reader_reading_history_position_type_check CHECK (position_type IN ('scroll', 'page')),
    CONSTRAINT reader_reading_history_position_check CHECK (position_value >= 0),
    CONSTRAINT reader_reading_history_progress_check CHECK (progress_percent >= 0 AND progress_percent <= 100)
);
CREATE INDEX reader_reading_history_reader_time_idx ON reader_reading_history (reader_id, last_read_at DESC);

CREATE TABLE reader_reading_preferences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    font_size integer NOT NULL DEFAULT 20,
    line_height numeric(4,2) NOT NULL DEFAULT 1.80,
    theme varchar(16) NOT NULL DEFAULT 'cream',
    reading_mode varchar(16) NOT NULL DEFAULT 'page',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_reading_preferences_reader_unique UNIQUE (reader_id),
    CONSTRAINT reader_reading_preferences_font_check CHECK (font_size BETWEEN 10 AND 48),
    CONSTRAINT reader_reading_preferences_line_check CHECK (line_height BETWEEN 1.00 AND 3.00),
    CONSTRAINT reader_reading_preferences_theme_check CHECK (theme IN ('cream', 'night', 'green')),
    CONSTRAINT reader_reading_preferences_mode_check CHECK (reading_mode IN ('scroll', 'page'))
);

CREATE TABLE reader_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    book_id bigint REFERENCES novel_books(id),
    chapter_id bigint REFERENCES novel_chapters(id),
    content text NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'pending',
    reply text NOT NULL DEFAULT '',
    replied_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_feedback_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT reader_feedback_status_check CHECK (status IN ('pending', 'replied')),
    CONSTRAINT reader_feedback_reply_check CHECK ((status = 'pending' AND reply = '') OR status = 'replied')
);
CREATE INDEX reader_feedback_reader_time_idx ON reader_feedback (reader_id, created_at DESC);

CREATE TABLE commerce_products (
    id bigint PRIMARY KEY,
    product_type varchar(20) NOT NULL,
    target_id bigint,
    product_name varchar(100) NOT NULL,
    price_coin bigint NOT NULL DEFAULT 0,
    allow_bonus_coin boolean NOT NULL DEFAULT false,
    duration_days integer,
    sale_status varchar(16) NOT NULL DEFAULT 'off_sale',
    sort_order integer NOT NULL DEFAULT 0,
    source_type varchar(16) NOT NULL DEFAULT 'legacy',
    source_ref varchar(128) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT commerce_products_type_check CHECK (product_type IN ('book', 'chapter', 'ad_free', 'membership')),
    CONSTRAINT commerce_products_price_check CHECK (price_coin >= 0),
    CONSTRAINT commerce_products_duration_check CHECK (duration_days IS NULL OR duration_days > 0),
    CONSTRAINT commerce_products_status_check CHECK (sale_status IN ('on_sale', 'off_sale')),
    CONSTRAINT commerce_products_sort_check CHECK (sort_order >= 0),
    CONSTRAINT commerce_products_name_not_blank CHECK (btrim(product_name) <> ''),
    CONSTRAINT commerce_products_target_check CHECK ((product_type IN ('book', 'chapter') AND target_id IS NOT NULL) OR (product_type IN ('ad_free', 'membership') AND target_id IS NULL))
);
CREATE UNIQUE INDEX commerce_products_target_unique ON commerce_products (product_type, COALESCE(target_id, 0));
CREATE INDEX commerce_products_status_idx ON commerce_products (product_type, sale_status, sort_order, id);

CREATE TABLE commerce_chapter_pricing_config (
    id bigint PRIMARY KEY,
    word_unit integer NOT NULL DEFAULT 1000,
    coin_unit bigint NOT NULL DEFAULT 1,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT commerce_chapter_pricing_singleton_check CHECK (id = 1),
    CONSTRAINT commerce_chapter_pricing_word_check CHECK (word_unit > 0),
    CONSTRAINT commerce_chapter_pricing_coin_check CHECK (coin_unit > 0)
);

CREATE TABLE commerce_membership_grants (
    id bigint PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    grant_type varchar(20) NOT NULL,
    starts_at timestamptz NOT NULL,
    expires_at timestamptz,
    permanent boolean NOT NULL DEFAULT false,
    status varchar(16) NOT NULL DEFAULT 'active',
    source_type varchar(20) NOT NULL DEFAULT 'legacy',
    source_ref varchar(128) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT commerce_membership_grants_type_check CHECK (grant_type IN ('purchase', 'admin', 'gift', 'legacy')),
    CONSTRAINT commerce_membership_grants_expiry_check CHECK (permanent OR expires_at IS NOT NULL),
    CONSTRAINT commerce_membership_grants_status_check CHECK (status IN ('active', 'disabled', 'expired'))
);
CREATE INDEX commerce_membership_grants_reader_idx ON commerce_membership_grants (reader_id, status, expires_at);

CREATE TABLE commerce_entitlements (
    id bigint PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    entitlement_type varchar(20) NOT NULL,
    target_id bigint NOT NULL DEFAULT 0,
    starts_at timestamptz NOT NULL,
    expires_at timestamptz,
    permanent boolean NOT NULL DEFAULT false,
    status varchar(16) NOT NULL DEFAULT 'active',
    source_type varchar(20) NOT NULL DEFAULT 'legacy',
    source_ref varchar(128) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT commerce_entitlements_type_check CHECK (entitlement_type IN ('book', 'chapter', 'ad_free', 'membership')),
    CONSTRAINT commerce_entitlements_target_check CHECK ((entitlement_type IN ('book', 'chapter') AND target_id > 0) OR (entitlement_type IN ('ad_free', 'membership') AND target_id = 0)),
    CONSTRAINT commerce_entitlements_expiry_check CHECK (permanent OR expires_at IS NOT NULL),
    CONSTRAINT commerce_entitlements_status_check CHECK (status IN ('active', 'disabled', 'expired')),
    CONSTRAINT commerce_entitlements_unique UNIQUE (reader_id, entitlement_type, target_id)
);
CREATE INDEX commerce_entitlements_reader_idx ON commerce_entitlements (reader_id, status, expires_at);

INSERT INTO commerce_chapter_pricing_config (id) VALUES (1) ON CONFLICT DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
