-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_chapters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL REFERENCES novel_books(id),
    chapter_no integer NOT NULL,
    chapter_name varchar(255) NOT NULL,
    word_count integer NOT NULL DEFAULT 0,
    is_vip boolean NOT NULL DEFAULT false,
    book_price_coin bigint NOT NULL DEFAULT 0,
    chapter_status varchar(16) NOT NULL DEFAULT 'enabled',
    ai_clean_status varchar(16) NOT NULL DEFAULT 'pending',
    source_type varchar(16) NOT NULL DEFAULT 'manual',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT novel_chapters_name_not_blank CHECK (btrim(chapter_name) <> ''),
    CONSTRAINT novel_chapters_no_check CHECK (chapter_no >= 0),
    CONSTRAINT novel_chapters_word_count_check CHECK (word_count >= 0),
    CONSTRAINT novel_chapters_price_check CHECK (book_price_coin >= 0),
    CONSTRAINT novel_chapters_status_check CHECK (chapter_status IN ('enabled','disabled')),
    CONSTRAINT novel_chapters_clean_status_check CHECK (ai_clean_status IN ('pending','cleaning','cleaned','discarded','failed','expired','skipped')),
    CONSTRAINT novel_chapters_source_check CHECK (source_type IN ('manual','legacy','txt_import','forum_crawl'))
);

CREATE UNIQUE INDEX novel_chapters_book_no_unique
    ON novel_chapters (book_id, chapter_no) WHERE deleted_at IS NULL;
CREATE INDEX novel_chapters_admin_list_idx
    ON novel_chapters (book_id, chapter_no, id) WHERE deleted_at IS NULL;
CREATE INDEX novel_chapters_reader_list_idx
    ON novel_chapters (book_id, chapter_no, id) WHERE deleted_at IS NULL AND chapter_status='enabled';

INSERT INTO sys_base_menus
    (id, created_at, updated_at, menu_level, parent_id, path, name, hidden, component, sort,
     active_name, keep_alive, default_menu, title, icon, close_tab, transition_type)
VALUES (1004, now(), now(), 1, 1000, 'chapters', 'NovelChapters', false, 'view/novel/chapters/index.vue', 4,
    '', true, false, '章节管理', 'document', false, '')
ON CONFLICT DO NOTHING;

INSERT INTO sys_authority_menus (sys_base_menu_id, sys_authority_authority_id)
VALUES (1004, 888) ON CONFLICT DO NOTHING;

INSERT INTO sys_apis (id, created_at, updated_at, path, description, api_group, method)
VALUES
    (1015, now(), now(), '/novel/chapters', '查询小说章节', '小说章节', 'GET'),
    (1016, now(), now(), '/novel/chapters/:id', '查询小说章节详情', '小说章节', 'GET'),
    (1017, now(), now(), '/novel/chapters/:id/content', '读取小说章节正文', '小说章节', 'GET'),
    (1018, now(), now(), '/novel/chapters', '新增小说章节', '小说章节', 'POST'),
    (1019, now(), now(), '/novel/chapters/:id', '修改小说章节', '小说章节', 'PUT'),
    (1020, now(), now(), '/novel/chapters/:id', '删除小说章节', '小说章节', 'DELETE')
ON CONFLICT DO NOTHING;

INSERT INTO casbin_rule (ptype, v0, v1, v2, v3, v4, v5)
VALUES
    ('p','888','/novel/chapters','GET','','',''),
    ('p','888','/novel/chapters/:id','GET','','',''),
    ('p','888','/novel/chapters/:id/content','GET','','',''),
    ('p','888','/novel/chapters','POST','','',''),
    ('p','888','/novel/chapters/:id','PUT','','',''),
    ('p','888','/novel/chapters/:id','DELETE','','','')
ON CONFLICT DO NOTHING;

SELECT setval('sys_base_menus_id_seq', GREATEST((SELECT max(id) FROM sys_base_menus), 1004), true);
SELECT setval('sys_apis_id_seq', GREATEST((SELECT max(id) FROM sys_apis), 1020), true);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
