-- +goose Up
-- +goose StatementBegin
CREATE TABLE reader_recharge_products (
    id bigint PRIMARY KEY,
    product_name varchar(100) NOT NULL,
    diamond_amount bigint NOT NULL,
    price_usdt numeric(20,2) NOT NULL,
    sale_status varchar(16) NOT NULL DEFAULT 'off_sale',
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_recharge_products_amount_check CHECK (diamond_amount > 0),
    CONSTRAINT reader_recharge_products_price_check CHECK (price_usdt > 0),
    CONSTRAINT reader_recharge_products_status_check CHECK (sale_status IN ('on_sale','off_sale'))
);
CREATE INDEX reader_recharge_products_sale_idx ON reader_recharge_products (sale_status, sort_order, id);

CREATE TABLE reader_recharge_settings (
    id bigint PRIMARY KEY CHECK (id = 1),
    custom_enabled boolean NOT NULL DEFAULT true,
    diamonds_per_usdt numeric(20,8) NOT NULL DEFAULT 7,
    min_diamond_amount bigint NOT NULL DEFAULT 7,
    max_diamond_amount bigint NOT NULL DEFAULT 70000,
    amount_scale integer NOT NULL DEFAULT 2,
    rounding_mode varchar(16) NOT NULL DEFAULT 'CEILING',
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_recharge_settings_rate_check CHECK (diamonds_per_usdt > 0),
    CONSTRAINT reader_recharge_settings_range_check CHECK (min_diamond_amount > 0 AND max_diamond_amount >= min_diamond_amount),
    CONSTRAINT reader_recharge_settings_scale_check CHECK (amount_scale BETWEEN 0 AND 8)
);
INSERT INTO reader_recharge_settings(id) VALUES (1);

CREATE TABLE reader_payment_channels (
    id bigint PRIMARY KEY,
    provider varchar(30) NOT NULL UNIQUE,
    enabled boolean NOT NULL DEFAULT false,
    currency varchar(20) NOT NULL DEFAULT 'usd',
    token varchar(20) NOT NULL DEFAULT 'usdt',
    network varchar(20) NOT NULL DEFAULT 'tron',
    updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO reader_payment_channels(id, provider) VALUES (1, 'epusdt');

CREATE TABLE reader_recharge_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no varchar(64) NOT NULL UNIQUE,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    request_id varchar(128) NOT NULL,
    source_type varchar(16) NOT NULL,
    product_id bigint REFERENCES reader_recharge_products(id),
    diamond_amount bigint NOT NULL,
    price_usdt numeric(20,2) NOT NULL,
    provider varchar(30) NOT NULL,
    currency varchar(20) NOT NULL,
    token varchar(20) NOT NULL,
    network varchar(20) NOT NULL,
    gateway_trade_id varchar(64),
    actual_amount numeric(24,8),
    receive_address varchar(255),
    payment_url varchar(1000),
    block_transaction_id varchar(128),
    status varchar(30) NOT NULL,
    gateway_status integer,
    wallet_ledger_id bigint,
    expire_time timestamptz,
    paid_time timestamptz,
    failure_code varchar(64),
    failure_message varchar(500),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_recharge_orders_request_unique UNIQUE (reader_id, request_id),
    CONSTRAINT reader_recharge_orders_source_check CHECK (source_type IN ('preset','custom')),
    CONSTRAINT reader_recharge_orders_amount_check CHECK (diamond_amount > 0 AND price_usdt > 0),
    CONSTRAINT reader_recharge_orders_status_check CHECK (status IN ('creating','pending','gateway_unknown','create_failed','superseded','expired','callback_exception','paid'))
);
CREATE INDEX reader_recharge_orders_reader_time_idx ON reader_recharge_orders (reader_id, created_at DESC, id DESC);
CREATE INDEX reader_recharge_orders_status_time_idx ON reader_recharge_orders (status, created_at);

CREATE TABLE reader_payment_callback_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider varchar(30) NOT NULL,
    recharge_order_id bigint REFERENCES reader_recharge_orders(id),
    merchant_order_no varchar(64) NOT NULL DEFAULT '',
    gateway_trade_id varchar(64) NOT NULL DEFAULT '',
    payload_hash char(64) NOT NULL,
    payload_snapshot jsonb,
    signature_valid boolean NOT NULL DEFAULT false,
    processing_result varchar(16) NOT NULL,
    failure_reason varchar(500) NOT NULL DEFAULT '',
    response_status integer NOT NULL,
    response_body varchar(64) NOT NULL DEFAULT '',
    request_time timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reader_payment_callback_logs_order_idx ON reader_payment_callback_logs (recharge_order_id, created_at);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
