-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_crawl_thread_candidate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES novel_crawl_forum_source(id),
    source_name varchar(100) NOT NULL,
    board_id bigint NOT NULL REFERENCES novel_crawl_forum_board(id),
    board_name varchar(100) NOT NULL,
    forum_thread_id varchar(128) NOT NULL,
    thread_title varchar(255) NOT NULL,
    display_title varchar(255) NOT NULL DEFAULT '',
    thread_url varchar(500) NOT NULL,
    author_id varchar(64) NOT NULL DEFAULT '',
    status varchar(20) NOT NULL DEFAULT 'pending',
    import_task_id bigint,
    target_book_id bigint,
    last_import_page_no integer,
    last_import_floor_id varchar(64),
    last_follow_time timestamptz,
    follow_count integer NOT NULL DEFAULT 0,
    follow_fail_reason varchar(1000) NOT NULL DEFAULT '',
    discover_time timestamptz NOT NULL DEFAULT now(),
    remark varchar(500) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_crawl_thread_candidate_source_thread_unique UNIQUE(source_id,forum_thread_id),
    CONSTRAINT novel_crawl_thread_candidate_status_check CHECK(status IN ('pending','importing','imported','skipped','failed')),
    CONSTRAINT novel_crawl_thread_candidate_follow_check CHECK(follow_count >= 0)
);
CREATE INDEX novel_crawl_thread_candidate_board_status_idx ON novel_crawl_thread_candidate(board_id,status,discover_time DESC,id DESC);
CREATE INDEX novel_crawl_thread_candidate_status_idx ON novel_crawl_thread_candidate(status,discover_time DESC,id DESC);
INSERT INTO sys_base_menus(id,created_at,updated_at,menu_level,parent_id,path,name,hidden,component,sort,active_name,keep_alive,default_menu,title,icon,close_tab,transition_type)
VALUES(1716,now(),now(),2,1000,'novelCrawlCandidates','NovelCrawlCandidates',false,'view/novel/crawlCandidates/index.vue',62,'',true,false,'帖子候选','list',false,'') ON CONFLICT DO NOTHING;
INSERT INTO sys_authority_menus(sys_base_menu_id,sys_authority_authority_id) VALUES(1716,888) ON CONFLICT DO NOTHING;
INSERT INTO sys_apis(id,created_at,updated_at,path,description,api_group,method) VALUES
(1750,now(),now(),'/novel/crawl/candidates','查询帖子候选','内容采集','GET'),
(1751,now(),now(),'/novel/crawl/candidates/:id','查询帖子候选详情','内容采集','GET'),
(1752,now(),now(),'/novel/crawl/candidates/skip','跳过帖子候选','内容采集','PUT'),
(1753,now(),now(),'/novel/crawl/candidates/restore','恢复帖子候选','内容采集','PUT'),
(1754,now(),now(),'/novel/crawl/candidates','删除帖子候选','内容采集','DELETE') ON CONFLICT DO NOTHING;
INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES
('p','888','/novel/crawl/candidates','GET','','',''),('p','888','/novel/crawl/candidates/:id','GET','','',''),('p','888','/novel/crawl/candidates/skip','PUT','','',''),('p','888','/novel/crawl/candidates/restore','PUT','','',''),('p','888','/novel/crawl/candidates','DELETE','','','') ON CONFLICT DO NOTHING;
SELECT setval('sys_base_menus_id_seq',GREATEST((SELECT max(id) FROM sys_base_menus),1716),true);
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1754),true);
-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
