-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_crawl_forum_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name varchar(100) NOT NULL,
    base_url varchar(500) NOT NULL,
    request_charset varchar(40) NOT NULL DEFAULT 'UTF-8',
    cookie_text text,
    user_agent varchar(500),
    request_interval_ms integer NOT NULL DEFAULT 1000,
    last_request_time timestamptz,
    enabled boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    remark varchar(500) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_crawl_forum_source_name_unique UNIQUE(source_name),
    CONSTRAINT novel_crawl_forum_source_interval_check CHECK(request_interval_ms BETWEEN 100 AND 86400000),
    CONSTRAINT novel_crawl_forum_source_sort_check CHECK(sort_order >= 0)
);
CREATE INDEX novel_crawl_forum_source_enabled_idx ON novel_crawl_forum_source(enabled,sort_order,id);
CREATE TABLE novel_crawl_forum_board (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES novel_crawl_forum_source(id),
    source_name varchar(100) NOT NULL,
    board_name varchar(100) NOT NULL,
    board_url varchar(500) NOT NULL,
    board_url_template varchar(500),
    last_cursor varchar(255),
    auto_follow_enabled boolean NOT NULL DEFAULT false,
    follow_interval_minutes integer NOT NULL DEFAULT 60,
    follow_import_limit integer NOT NULL DEFAULT 20,
    last_follow_time timestamptz,
    enabled boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    remark varchar(500) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_crawl_forum_board_source_name_unique UNIQUE(source_id,board_name),
    CONSTRAINT novel_crawl_forum_board_interval_check CHECK(follow_interval_minutes > 0 AND follow_import_limit > 0)
);
CREATE INDEX novel_crawl_forum_board_source_idx ON novel_crawl_forum_board(source_id,enabled,sort_order,id);
INSERT INTO sys_base_menus(id,created_at,updated_at,menu_level,parent_id,path,name,hidden,component,sort,active_name,keep_alive,default_menu,title,icon,close_tab,transition_type)
VALUES(1714,now(),now(),2,1000,'novelCrawlSources','NovelCrawlSources',false,'view/novel/crawlSources/index.vue',60,'',true,false,'论坛来源','connection',false,'') ON CONFLICT DO NOTHING;
INSERT INTO sys_authority_menus(sys_base_menu_id,sys_authority_authority_id) VALUES(1714,888) ON CONFLICT DO NOTHING;
INSERT INTO sys_apis(id,created_at,updated_at,path,description,api_group,method) VALUES(1742,now(),now(),'/novel/crawl/sources','查询论坛来源','内容采集','GET'),(1743,now(),now(),'/novel/crawl/sources','新增论坛来源','内容采集','POST'),(1744,now(),now(),'/novel/crawl/sources/:id','修改论坛来源','内容采集','PUT'),(1745,now(),now(),'/novel/crawl/sources/:id','删除论坛来源','内容采集','DELETE') ON CONFLICT DO NOTHING;
INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES('p','888','/novel/crawl/sources','GET','','',''),('p','888','/novel/crawl/sources','POST','','',''),('p','888','/novel/crawl/sources/:id','PUT','','',''),('p','888','/novel/crawl/sources/:id','DELETE','','','') ON CONFLICT DO NOTHING;
SELECT setval('sys_base_menus_id_seq',GREATEST((SELECT max(id) FROM sys_base_menus),1714),true);
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1745),true);
-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
