-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_crawl_import_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id bigint NOT NULL REFERENCES novel_crawl_thread_candidate(id),
    platform_job_id bigint REFERENCES platform_jobs(id),
    source_id bigint NOT NULL REFERENCES novel_crawl_forum_source(id),
    source_name varchar(100) NOT NULL,
    board_id bigint NOT NULL REFERENCES novel_crawl_forum_board(id),
    board_name varchar(100) NOT NULL,
    forum_thread_id varchar(128) NOT NULL,
    thread_title varchar(255) NOT NULL,
    display_title varchar(255) NOT NULL DEFAULT '',
    thread_url varchar(500) NOT NULL,
    target_book_id bigint,
    import_mode varchar(20) NOT NULL DEFAULT 'create',
    merge_strategy varchar(30) NOT NULL DEFAULT 'source_thread',
    status varchar(20) NOT NULL DEFAULT 'pending',
    total_chapter_count integer NOT NULL DEFAULT 0,
    imported_chapter_count integer NOT NULL DEFAULT 0,
    quality_status varchar(20) NOT NULL DEFAULT 'pending',
    quality_summary varchar(1000) NOT NULL DEFAULT '',
    empty_chapter_count integer NOT NULL DEFAULT 0,
    duplicate_chapter_count integer NOT NULL DEFAULT 0,
    fail_reason varchar(1000) NOT NULL DEFAULT '',
    operator_name varchar(64) NOT NULL DEFAULT '',
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    start_time timestamptz,
    end_time timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_crawl_import_task_mode_check CHECK(import_mode IN ('create','incremental')),
    CONSTRAINT novel_crawl_import_task_merge_check CHECK(merge_strategy IN ('source_thread','same_title')),
    CONSTRAINT novel_crawl_import_task_status_check CHECK(status IN ('pending','running','succeeded','failed','cancelled')),
    CONSTRAINT novel_crawl_import_task_quality_check CHECK(quality_status IN ('pending','passed','warning','failed')),
    CONSTRAINT novel_crawl_import_task_attempt_check CHECK(attempt_count >= 0 AND max_attempts > 0)
);
CREATE INDEX novel_crawl_import_task_status_idx ON novel_crawl_import_task(status,created_at DESC,id DESC);
CREATE INDEX novel_crawl_import_task_candidate_idx ON novel_crawl_import_task(candidate_id,status);
CREATE UNIQUE INDEX novel_crawl_import_task_active_candidate_idx ON novel_crawl_import_task(candidate_id) WHERE status IN ('pending','running');
INSERT INTO sys_base_menus(id,created_at,updated_at,menu_level,parent_id,path,name,hidden,component,sort,active_name,keep_alive,default_menu,title,icon,close_tab,transition_type)
VALUES(1717,now(),now(),2,1000,'novelCrawlImportTasks','NovelCrawlImportTasks',false,'view/novel/crawlImportTasks/index.vue',63,'',true,false,'导入任务','tickets',false,'') ON CONFLICT DO NOTHING;
INSERT INTO sys_authority_menus(sys_base_menu_id,sys_authority_authority_id) VALUES(1717,888) ON CONFLICT DO NOTHING;
INSERT INTO sys_apis(id,created_at,updated_at,path,description,api_group,method) VALUES
(1755,now(),now(),'/novel/crawl/importTasks','查询导入任务','内容采集','GET'),(1756,now(),now(),'/novel/crawl/importTasks/:id','查询导入任务详情','内容采集','GET'),(1757,now(),now(),'/novel/crawl/importTasks','创建导入任务','内容采集','POST'),(1758,now(),now(),'/novel/crawl/importTasks/:id/retry','重试导入任务','内容采集','POST'),(1759,now(),now(),'/novel/crawl/importTasks/:id/cancel','取消导入任务','内容采集','POST') ON CONFLICT DO NOTHING;
INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES('p','888','/novel/crawl/importTasks','GET','','',''),('p','888','/novel/crawl/importTasks/:id','GET','','',''),('p','888','/novel/crawl/importTasks','POST','','',''),('p','888','/novel/crawl/importTasks/:id/retry','POST','','',''),('p','888','/novel/crawl/importTasks/:id/cancel','POST','','','') ON CONFLICT DO NOTHING;
SELECT setval('sys_base_menus_id_seq',GREATEST((SELECT max(id) FROM sys_base_menus),1717),true);
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1759),true);
-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
