-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_chapter_clean_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled boolean NOT NULL DEFAULT false,
    ai_config_id bigint NOT NULL REFERENCES novel_ai_config(id),
    refusal_fallback_ai_config_id bigint REFERENCES novel_ai_config(id),
    system_prompt text NOT NULL,
    temperature numeric(4,2) NOT NULL DEFAULT 0.10 CHECK (temperature BETWEEN 0 AND 2),
    max_tokens integer CHECK (max_tokens IS NULL OR max_tokens >= 0),
    min_chapter_word_count integer NOT NULL DEFAULT 0 CHECK (min_chapter_word_count >= 0),
    min_cleaned_text_percent integer NOT NULL DEFAULT 70 CHECK (min_cleaned_text_percent BETWEEN 0 AND 100),
    auto_success_word_count integer NOT NULL DEFAULT 3000 CHECK (auto_success_word_count >= 0),
    timeout_seconds integer NOT NULL DEFAULT 120 CHECK (timeout_seconds BETWEEN 1 AND 1800),
    request_interval_ms integer NOT NULL DEFAULT 0 CHECK (request_interval_ms BETWEEN 0 AND 600000),
    retry_count integer NOT NULL DEFAULT 1 CHECK (retry_count BETWEEN 0 AND 20),
    continue_on_failure boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_novel_chapter_clean_singleton ON novel_chapter_clean_config ((true));

CREATE TABLE novel_chapter_clean_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL REFERENCES novel_books(id),
    book_name varchar(200) NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('running','completed','stopped','failed')),
    force_reclean boolean NOT NULL DEFAULT false,
    total_count integer NOT NULL DEFAULT 0,
    processed_count integer NOT NULL DEFAULT 0,
    success_count integer NOT NULL DEFAULT 0,
    discard_count integer NOT NULL DEFAULT 0,
    fail_count integer NOT NULL DEFAULT 0,
    skip_count integer NOT NULL DEFAULT 0,
    all_chapters_discarded boolean NOT NULL DEFAULT false,
    stop_requested boolean NOT NULL DEFAULT false,
    operator_name varchar(64) NOT NULL DEFAULT '',
    error_summary varchar(1000) NOT NULL DEFAULT '',
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_novel_clean_task_book ON novel_chapter_clean_task(book_id,id DESC);
CREATE INDEX idx_novel_clean_task_status ON novel_chapter_clean_task(status,id);

CREATE TABLE novel_chapter_clean_result (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL REFERENCES novel_chapter_clean_task(id),
    book_id bigint NOT NULL REFERENCES novel_books(id),
    chapter_id bigint NOT NULL REFERENCES novel_chapters(id),
    source_chapter_no integer NOT NULL,
    content_type varchar(30) NOT NULL DEFAULT '',
    is_novel_body boolean,
    cleaned_chapter_name varchar(255) NOT NULL DEFAULT '',
    cleaned_object_id bigint REFERENCES novel_objects(id),
    original_object_id bigint REFERENCES novel_objects(id),
    chapter_summary text NOT NULL DEFAULT '',
    cleaned_word_count integer NOT NULL DEFAULT 0,
    removed_non_novel boolean,
    confidence numeric(5,4),
    raw_response text NOT NULL DEFAULT '',
    raw_response_expires_at timestamptz,
    status varchar(24) NOT NULL CHECK (status IN ('success','discarded','failed','manual_discarded','skipped','expired','pending_review')),
    error_message varchar(1000) NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_novel_clean_result_active ON novel_chapter_clean_result(chapter_id) WHERE active;
CREATE INDEX idx_novel_clean_result_task ON novel_chapter_clean_result(task_id,id);
CREATE INDEX idx_novel_clean_result_filter ON novel_chapter_clean_result(book_id,status,active,id DESC);

INSERT INTO sys_base_menus
    (id,created_at,updated_at,menu_level,parent_id,path,name,hidden,component,sort,
     active_name,keep_alive,default_menu,title,icon,close_tab,transition_type)
VALUES (1722,now(),now(),2,1000,'novelChapterClean','NovelChapterClean',false,
    'view/novel/chapterClean/index.vue',68,'',true,false,'章节清洗','magic-stick',false,'')
ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_authority_menus(sys_base_menu_id,sys_authority_authority_id) VALUES(1722,888) ON CONFLICT DO NOTHING;

INSERT INTO sys_apis (id,created_at,updated_at,path,description,api_group,method) VALUES
    (1779,now(),now(),'/novel/chapterClean/config','查询章节清洗配置','内容生产','GET'),
    (1780,now(),now(),'/novel/chapterClean/config','保存章节清洗配置','内容生产','PUT'),
    (1781,now(),now(),'/novel/chapterClean/tasks','查询章节清洗任务','内容生产','GET'),
    (1782,now(),now(),'/novel/chapterClean/tasks/:id','查询章节清洗任务详情','内容生产','GET'),
    (1783,now(),now(),'/novel/chapterClean/tasks','启动章节清洗任务','内容生产','POST'),
    (1784,now(),now(),'/novel/chapterClean/tasks/:id/stop','停止章节清洗任务','内容生产','POST'),
    (1785,now(),now(),'/novel/chapterClean/tasks/:id/resume','续跑章节清洗任务','内容生产','POST'),
    (1786,now(),now(),'/novel/chapterClean/results','查询章节清洗结果','内容生产','GET'),
    (1787,now(),now(),'/novel/chapterClean/results/:id','查询章节清洗结果详情','内容生产','GET'),
    (1788,now(),now(),'/novel/chapterClean/results/:id/review','审核章节清洗结果','内容生产','PUT'),
    (1789,now(),now(),'/novel/chapterClean/results/:id/reclean','重新清洗章节','内容生产','POST')
ON CONFLICT (id) DO NOTHING;

INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES
    ('p','888','/novel/chapterClean/config','GET','','',''),('p','888','/novel/chapterClean/config','PUT','','',''),
    ('p','888','/novel/chapterClean/tasks','GET','','',''),('p','888','/novel/chapterClean/tasks/:id','GET','','',''),
    ('p','888','/novel/chapterClean/tasks','POST','','',''),('p','888','/novel/chapterClean/tasks/:id/stop','POST','','',''),
    ('p','888','/novel/chapterClean/tasks/:id/resume','POST','','',''),('p','888','/novel/chapterClean/results','GET','','',''),
    ('p','888','/novel/chapterClean/results/:id','GET','','',''),('p','888','/novel/chapterClean/results/:id/review','PUT','','',''),
    ('p','888','/novel/chapterClean/results/:id/reclean','POST','','','')
ON CONFLICT DO NOTHING;
SELECT setval('sys_base_menus_id_seq',GREATEST((SELECT max(id) FROM sys_base_menus),1722),true);
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1789),true);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
