-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_ai_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name varchar(100) NOT NULL,
    base_url varchar(2048) NOT NULL,
    stream_mode varchar(20) NOT NULL DEFAULT 'AUTO',
    failure_threshold integer NOT NULL DEFAULT 5,
    current_model_id bigint,
    consecutive_failures integer NOT NULL DEFAULT 0,
    state_version bigint NOT NULL DEFAULT 0,
    secret_env_name varchar(128) NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    remark varchar(500) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT novel_ai_config_stream_mode_check CHECK(stream_mode IN ('AUTO','STREAM','NON_STREAM')),
    CONSTRAINT novel_ai_config_failure_threshold_check CHECK(failure_threshold BETWEEN 1 AND 1000),
    CONSTRAINT novel_ai_config_consecutive_failures_check CHECK(consecutive_failures >= 0),
    CONSTRAINT novel_ai_config_state_version_check CHECK(state_version >= 0),
    CONSTRAINT novel_ai_config_secret_env_name_check CHECK(secret_env_name = '' OR secret_env_name ~ '^MOONBOOK_AI_[A-Z0-9_]+_API_KEY$')
);
CREATE INDEX novel_ai_config_list_idx ON novel_ai_config(deleted_at,enabled,id);
CREATE INDEX novel_ai_config_name_idx ON novel_ai_config(config_name) WHERE deleted_at IS NULL;

CREATE TABLE novel_ai_config_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_config_id bigint NOT NULL REFERENCES novel_ai_config(id),
    model_name varchar(100) NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_ai_config_model_owner_unique UNIQUE(id,ai_config_id),
    CONSTRAINT novel_ai_config_model_name_unique UNIQUE(ai_config_id,model_name),
    CONSTRAINT novel_ai_config_model_order_unique UNIQUE(ai_config_id,sort_order),
    CONSTRAINT novel_ai_config_model_order_check CHECK(sort_order > 0)
);
CREATE INDEX novel_ai_config_model_config_idx ON novel_ai_config_model(ai_config_id,sort_order,id);

ALTER TABLE novel_ai_config ADD CONSTRAINT novel_ai_config_current_model_fk
    FOREIGN KEY(current_model_id,id) REFERENCES novel_ai_config_model(id,ai_config_id);

INSERT INTO sys_base_menus
    (id,created_at,updated_at,menu_level,parent_id,path,name,hidden,component,sort,
     active_name,keep_alive,default_menu,title,icon,close_tab,transition_type)
VALUES(1721,now(),now(),2,1000,'novelAiConfigs','NovelAiConfigs',false,
    'view/novel/aiConfigs/index.vue',67,'',true,false,'AI配置','cpu',false,'')
ON CONFLICT DO NOTHING;
INSERT INTO sys_authority_menus(sys_base_menu_id,sys_authority_authority_id) VALUES(1721,888) ON CONFLICT DO NOTHING;

INSERT INTO sys_apis(id,created_at,updated_at,path,description,api_group,method) VALUES
    (1772,now(),now(),'/novel/aiConfigs','查询AI配置','内容生产','GET'),
    (1773,now(),now(),'/novel/aiConfigs/enabledOptions','查询启用AI配置','内容生产','GET'),
    (1774,now(),now(),'/novel/aiConfigs/:id','查询AI配置详情','内容生产','GET'),
    (1775,now(),now(),'/novel/aiConfigs','新增AI配置','内容生产','POST'),
    (1776,now(),now(),'/novel/aiConfigs/:id','修改AI配置','内容生产','PUT'),
    (1777,now(),now(),'/novel/aiConfigs/:id/resetModelState','重置AI模型状态','内容生产','POST'),
    (1778,now(),now(),'/novel/aiConfigs/:id','删除AI配置','内容生产','DELETE')
ON CONFLICT DO NOTHING;
INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES
    ('p','888','/novel/aiConfigs','GET','','',''),
    ('p','888','/novel/aiConfigs/enabledOptions','GET','','',''),
    ('p','888','/novel/aiConfigs/:id','GET','','',''),
    ('p','888','/novel/aiConfigs','POST','','',''),
    ('p','888','/novel/aiConfigs/:id','PUT','','',''),
    ('p','888','/novel/aiConfigs/:id/resetModelState','POST','','',''),
    ('p','888','/novel/aiConfigs/:id','DELETE','','','')
ON CONFLICT DO NOTHING;
SELECT setval('sys_base_menus_id_seq',GREATEST((SELECT max(id) FROM sys_base_menus),1721),true);
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1778),true);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
