-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_txt_import_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_book_id bigint NOT NULL REFERENCES novel_books(id),
    platform_job_id bigint REFERENCES platform_jobs(id),
    original_filename varchar(255) NOT NULL,
    object_key varchar(500) NOT NULL,
    object_sha256 char(64) NOT NULL,
    object_byte_size bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    quality_status varchar(20) NOT NULL DEFAULT 'pending',
    quality_summary varchar(1000) NOT NULL DEFAULT '',
    total_chapter_count integer NOT NULL DEFAULT 0,
    imported_chapter_count integer NOT NULL DEFAULT 0,
    empty_chapter_count integer NOT NULL DEFAULT 0,
    duplicate_chapter_count integer NOT NULL DEFAULT 0,
    fail_reason varchar(1000) NOT NULL DEFAULT '',
    operator_name varchar(64) NOT NULL DEFAULT '',
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    start_time timestamptz,
    end_time timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_txt_import_status_check CHECK(status IN ('pending','running','succeeded','failed','cancelled')),
    CONSTRAINT novel_txt_import_quality_check CHECK(quality_status IN ('pending','passed','warning','failed')),
    CONSTRAINT novel_txt_import_size_check CHECK(object_byte_size > 0 AND object_byte_size <= 16777215),
    CONSTRAINT novel_txt_import_attempt_check CHECK(attempt_count >= 0 AND max_attempts > 0)
);
CREATE INDEX novel_txt_import_task_status_idx ON novel_txt_import_task(status,created_at DESC,id DESC);
CREATE INDEX novel_txt_import_task_book_idx ON novel_txt_import_task(target_book_id,created_at DESC,id DESC);
CREATE UNIQUE INDEX novel_txt_import_object_unique ON novel_txt_import_task(target_book_id,object_sha256);
INSERT INTO sys_base_menus(id,created_at,updated_at,menu_level,parent_id,path,name,hidden,component,sort,active_name,keep_alive,default_menu,title,icon,close_tab,transition_type)
VALUES(1718,now(),now(),2,1000,'novelTxtImports','NovelTxtImports',false,'view/novel/txtImports/index.vue',64,'',true,false,'TXT导入','upload',false,'') ON CONFLICT DO NOTHING;
INSERT INTO sys_authority_menus(sys_base_menu_id,sys_authority_authority_id) VALUES(1718,888) ON CONFLICT DO NOTHING;
INSERT INTO sys_apis(id,created_at,updated_at,path,description,api_group,method) VALUES
(1760,now(),now(),'/novel/txtImports','查询TXT导入任务','内容生产','GET'),(1761,now(),now(),'/novel/txtImports','上传TXT导入文件','内容生产','POST'),(1762,now(),now(),'/novel/txtImports/:id','查询TXT导入详情','内容生产','GET'),(1763,now(),now(),'/novel/txtImports/:id/preview','预览TXT导入内容','内容生产','GET'),(1764,now(),now(),'/novel/txtImports/:id/retry','重试TXT导入','内容生产','POST'),(1765,now(),now(),'/novel/txtImports/:id/cancel','取消TXT导入','内容生产','POST') ON CONFLICT DO NOTHING;
INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES
('p','888','/novel/txtImports','GET','','',''),('p','888','/novel/txtImports','POST','','',''),('p','888','/novel/txtImports/:id','GET','','',''),('p','888','/novel/txtImports/:id/preview','GET','','',''),('p','888','/novel/txtImports/:id/retry','POST','','',''),('p','888','/novel/txtImports/:id/cancel','POST','','','') ON CONFLICT DO NOTHING;
SELECT setval('sys_base_menus_id_seq',GREATEST((SELECT max(id) FROM sys_base_menus),1718),true);
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1765),true);
-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
