-- +goose Up
-- +goose StatementBegin
ALTER TABLE novel_crawl_import_task ADD COLUMN thread_created_at timestamptz;

ALTER TABLE novel_books DROP CONSTRAINT novel_books_source_check;
ALTER TABLE novel_books ADD CONSTRAINT novel_books_source_check
    CHECK (source_type IN ('manual','legacy','txt_import','forum_crawl','book_merge'));

ALTER TABLE novel_chapters DROP CONSTRAINT novel_chapters_source_check;
ALTER TABLE novel_chapters ADD CONSTRAINT novel_chapters_source_check
    CHECK (source_type IN ('manual','legacy','txt_import','forum_crawl','book_merge'));

CREATE TABLE novel_book_merge_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_book_id bigint,
    target_book_name varchar(100) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'running',
    source_count integer NOT NULL,
    chapter_count integer NOT NULL,
    included_chapter_count integer NOT NULL,
    excluded_chapter_count integer NOT NULL,
    duplicate_chapter_count integer NOT NULL,
    content_policy varchar(30) NOT NULL DEFAULT 'clean_first',
    sort_policy varchar(60) NOT NULL DEFAULT 'thread_created_at_then_chapter_no',
    source_archive_mode varchar(40) NOT NULL DEFAULT 'draft_after_success',
    operator_name varchar(64) NOT NULL DEFAULT '',
    error_summary varchar(1000) NOT NULL DEFAULT '',
    start_time timestamptz NOT NULL DEFAULT now(),
    end_time timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_book_merge_task_status_check CHECK(status IN ('running','succeeded','failed')),
    CONSTRAINT novel_book_merge_task_counts_check CHECK(
        source_count >= 2 AND chapter_count > 0 AND included_chapter_count > 0
        AND excluded_chapter_count >= 0 AND duplicate_chapter_count >= 0
        AND chapter_count = included_chapter_count + excluded_chapter_count
    )
);
CREATE INDEX novel_book_merge_task_status_idx ON novel_book_merge_task(status,created_at DESC,id DESC);
CREATE INDEX novel_book_merge_task_target_idx ON novel_book_merge_task(target_book_id) WHERE target_book_id IS NOT NULL;

CREATE TABLE novel_book_merge_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL REFERENCES novel_book_merge_task(id),
    source_book_id bigint NOT NULL REFERENCES novel_books(id),
    source_book_name varchar(100) NOT NULL,
    source_author_name varchar(100) NOT NULL,
    source_import_task_id bigint NOT NULL REFERENCES novel_crawl_import_task(id),
    source_name varchar(100) NOT NULL,
    source_thread_id varchar(128) NOT NULL,
    source_thread_title varchar(255) NOT NULL,
    source_thread_url varchar(500) NOT NULL,
    sort_time timestamptz NOT NULL,
    sort_time_source varchar(40) NOT NULL,
    source_order integer NOT NULL,
    old_publish_status varchar(16) NOT NULL,
    archived_publish_status varchar(16) NOT NULL,
    archive_time timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_book_merge_source_unique UNIQUE(task_id,source_book_id),
    CONSTRAINT novel_book_merge_source_sort_source_check CHECK(sort_time_source IN ('thread_created_at','import_task_created_at')),
    CONSTRAINT novel_book_merge_source_order_check CHECK(source_order > 0)
);
CREATE INDEX novel_book_merge_source_book_idx ON novel_book_merge_source(source_book_id,task_id);

CREATE TABLE novel_book_merge_chapter (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL REFERENCES novel_book_merge_task(id),
    source_book_id bigint NOT NULL REFERENCES novel_books(id),
    source_chapter_id bigint NOT NULL REFERENCES novel_chapters(id),
    source_chapter_no integer NOT NULL,
    source_chapter_name varchar(255) NOT NULL,
    source_object_id bigint NOT NULL REFERENCES novel_objects(id),
    target_book_id bigint,
    target_chapter_id bigint,
    target_chapter_no integer,
    target_chapter_name varchar(255),
    target_object_id bigint REFERENCES novel_objects(id),
    content_source varchar(30) NOT NULL,
    clean_result_id bigint,
    sort_time timestamptz NOT NULL,
    sort_time_source varchar(40) NOT NULL,
    duplicate_flag boolean NOT NULL DEFAULT false,
    duplicate_reason varchar(255) NOT NULL DEFAULT '',
    excluded boolean NOT NULL DEFAULT false,
    exclude_reason varchar(255) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_book_merge_chapter_unique UNIQUE(task_id,source_chapter_id),
    CONSTRAINT novel_book_merge_chapter_content_source_check CHECK(content_source IN ('clean_result','original')),
    CONSTRAINT novel_book_merge_chapter_target_check CHECK(
        (excluded AND target_book_id IS NULL AND target_chapter_id IS NULL AND target_chapter_no IS NULL AND target_object_id IS NULL)
        OR
        (NOT excluded AND target_book_id IS NOT NULL AND target_chapter_id IS NOT NULL AND target_chapter_no IS NOT NULL AND target_object_id IS NOT NULL)
    )
);
CREATE INDEX novel_book_merge_chapter_task_idx ON novel_book_merge_chapter(task_id,excluded,target_chapter_no,source_chapter_no,id);
CREATE INDEX novel_book_merge_chapter_source_idx ON novel_book_merge_chapter(source_chapter_id,task_id);
CREATE INDEX novel_book_merge_chapter_target_idx ON novel_book_merge_chapter(target_chapter_id) WHERE target_chapter_id IS NOT NULL;

INSERT INTO sys_base_menus
    (id,created_at,updated_at,menu_level,parent_id,path,name,hidden,component,sort,
     active_name,keep_alive,default_menu,title,icon,close_tab,transition_type)
VALUES(1720,now(),now(),2,1000,'novelBookMerges','NovelBookMerges',false,
    'view/novel/bookMerges/index.vue',66,'',true,false,'书籍合并','connection',false,'')
ON CONFLICT DO NOTHING;
INSERT INTO sys_authority_menus(sys_base_menu_id,sys_authority_authority_id) VALUES(1720,888) ON CONFLICT DO NOTHING;

INSERT INTO sys_apis(id,created_at,updated_at,path,description,api_group,method) VALUES
    (1767,now(),now(),'/novel/bookMerges','查询书籍合并任务','内容生产','GET'),
    (1768,now(),now(),'/novel/bookMerges/:id','查询书籍合并详情','内容生产','GET'),
    (1769,now(),now(),'/novel/bookMerges/eligibleBooks','查询可合并书籍','内容生产','GET'),
    (1770,now(),now(),'/novel/bookMerges/preview','预览书籍合并','内容生产','POST'),
    (1771,now(),now(),'/novel/bookMerges/execute','执行书籍合并','内容生产','POST')
ON CONFLICT DO NOTHING;
INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES
    ('p','888','/novel/bookMerges','GET','','',''),
    ('p','888','/novel/bookMerges/:id','GET','','',''),
    ('p','888','/novel/bookMerges/eligibleBooks','GET','','',''),
    ('p','888','/novel/bookMerges/preview','POST','','',''),
    ('p','888','/novel/bookMerges/execute','POST','','','')
ON CONFLICT DO NOTHING;
SELECT setval('sys_base_menus_id_seq',GREATEST((SELECT max(id) FROM sys_base_menus),1720),true);
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1771),true);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
