-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_crawl_fetch_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint REFERENCES novel_crawl_import_task(id),
    source_id bigint REFERENCES novel_crawl_forum_source(id),
    source_name varchar(100), board_id bigint REFERENCES novel_crawl_forum_board(id), board_name varchar(100),
    thread_url varchar(500), request_url varchar(500), stage varchar(30) NOT NULL, status varchar(20) NOT NULL,
    http_status integer, response_bytes integer, elapsed_ms integer, item_count integer, target_book_id bigint,
    message varchar(1000) NOT NULL DEFAULT '', detail_json jsonb, created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT novel_crawl_fetch_log_status_check CHECK(status IN ('started','succeeded','failed','skipped')),
    CONSTRAINT novel_crawl_fetch_log_stage_check CHECK(stage IN ('discover','thread','chapter','import','quality'))
);
CREATE INDEX novel_crawl_fetch_log_task_idx ON novel_crawl_fetch_log(task_id,created_at DESC,id DESC);
CREATE INDEX novel_crawl_fetch_log_status_idx ON novel_crawl_fetch_log(status,created_at DESC,id DESC);
INSERT INTO sys_base_menus(id,created_at,updated_at,menu_level,parent_id,path,name,hidden,component,sort,active_name,keep_alive,default_menu,title,icon,close_tab,transition_type)
VALUES(1718,now(),now(),2,1000,'novelCrawlFetchLogs','NovelCrawlFetchLogs',false,'view/novel/crawlFetchLogs/index.vue',64,'',true,false,'抓取日志','document',false,'') ON CONFLICT DO NOTHING;
INSERT INTO sys_authority_menus(sys_base_menu_id,sys_authority_authority_id) VALUES(1718,888) ON CONFLICT DO NOTHING;
INSERT INTO sys_apis(id,created_at,updated_at,path,description,api_group,method) VALUES(1760,now(),now(),'/novel/crawl/fetchLogs','查询抓取日志','内容采集','GET'),(1761,now(),now(),'/novel/crawl/fetchLogs/:id','查询抓取日志详情','内容采集','GET') ON CONFLICT DO NOTHING;
INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES('p','888','/novel/crawl/fetchLogs','GET','','',''),('p','888','/novel/crawl/fetchLogs/:id','GET','','','') ON CONFLICT DO NOTHING;
SELECT setval('sys_base_menus_id_seq',GREATEST((SELECT max(id) FROM sys_base_menus),1718),true);
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1761),true);
-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
