-- +goose Up
-- +goose StatementBegin
ALTER TABLE reader_wallets
    ADD COLUMN source_type varchar(16) NOT NULL DEFAULT 'runtime',
    ADD COLUMN source_ref varchar(128);

ALTER TABLE reader_wallet_ledgers
    ADD COLUMN source_type varchar(16) NOT NULL DEFAULT 'runtime',
    ADD COLUMN source_ref varchar(128);
CREATE UNIQUE INDEX reader_wallet_ledgers_legacy_source_uidx
    ON reader_wallet_ledgers(source_type, source_ref)
    WHERE source_type='legacy' AND source_ref IS NOT NULL;

ALTER TABLE reader_purchase_orders
    ADD COLUMN operator_id bigint,
    ADD COLUMN source_type varchar(16) NOT NULL DEFAULT 'runtime',
    ADD COLUMN source_ref varchar(128);
ALTER TABLE reader_purchase_orders DROP CONSTRAINT reader_purchase_orders_type_check;
ALTER TABLE reader_purchase_orders ADD CONSTRAINT reader_purchase_orders_type_check
    CHECK (order_type IN ('membership','chapter','book','ad_free','mock_recharge'));
ALTER TABLE reader_purchase_orders DROP CONSTRAINT reader_purchase_orders_status_check;
ALTER TABLE reader_purchase_orders ADD CONSTRAINT reader_purchase_orders_status_check
    CHECK (status IN ('pending','paid','closed','failed','refunded'));
CREATE UNIQUE INDEX reader_purchase_orders_legacy_source_uidx
    ON reader_purchase_orders(source_type, source_ref)
    WHERE source_type='legacy' AND source_ref IS NOT NULL;

ALTER TABLE reader_checkin_reward_rules
    ADD COLUMN source_type varchar(16) NOT NULL DEFAULT 'runtime',
    ADD COLUMN source_ref varchar(128);
ALTER TABLE reader_checkin_records
    ADD COLUMN source_type varchar(16) NOT NULL DEFAULT 'runtime',
    ADD COLUMN source_ref varchar(128);
CREATE UNIQUE INDEX reader_checkin_records_legacy_source_uidx
    ON reader_checkin_records(source_type, source_ref)
    WHERE source_type='legacy' AND source_ref IS NOT NULL;

ALTER TABLE reader_recharge_products
    ADD COLUMN source_type varchar(16) NOT NULL DEFAULT 'runtime',
    ADD COLUMN source_ref varchar(128);
ALTER TABLE reader_recharge_settings
    ADD COLUMN source_type varchar(16) NOT NULL DEFAULT 'runtime',
    ADD COLUMN source_ref varchar(128);
ALTER TABLE reader_payment_channels
    ADD COLUMN source_type varchar(16) NOT NULL DEFAULT 'runtime',
    ADD COLUMN source_ref varchar(128);
ALTER TABLE reader_recharge_orders
    ADD COLUMN legacy_channel_id bigint,
    ADD COLUMN legacy_payment_credential_id bigint,
    ADD COLUMN merchant_pid_sha256 char(64),
    ADD COLUMN legacy_source_ref varchar(128);
CREATE UNIQUE INDEX reader_recharge_orders_legacy_source_uidx
    ON reader_recharge_orders(legacy_source_ref)
    WHERE legacy_source_ref IS NOT NULL;
ALTER TABLE reader_payment_callback_logs
    ADD COLUMN source_ip_sha256 char(64),
    ADD COLUMN source_type varchar(16) NOT NULL DEFAULT 'runtime',
    ADD COLUMN source_ref varchar(128);
CREATE UNIQUE INDEX reader_payment_callback_logs_legacy_source_uidx
    ON reader_payment_callback_logs(source_type, source_ref)
    WHERE source_type='legacy' AND source_ref IS NOT NULL;

CREATE TABLE reader_bonus_coin_buckets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    source_kind varchar(40) NOT NULL,
    source_id bigint,
    original_amount bigint NOT NULL,
    remaining_amount bigint NOT NULL,
    expires_at timestamptz NOT NULL,
    status varchar(16) NOT NULL,
    source_type varchar(16) NOT NULL DEFAULT 'runtime',
    source_ref varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_bonus_coin_buckets_amount_check CHECK (original_amount >= 0 AND remaining_amount >= 0 AND remaining_amount <= original_amount),
    CONSTRAINT reader_bonus_coin_buckets_status_check CHECK (status IN ('active','depleted','expired'))
);
CREATE INDEX reader_bonus_coin_buckets_reader_expiry_idx ON reader_bonus_coin_buckets(reader_id,status,expires_at,id);
CREATE UNIQUE INDEX reader_bonus_coin_buckets_legacy_source_uidx ON reader_bonus_coin_buckets(source_type,source_ref) WHERE source_type='legacy' AND source_ref IS NOT NULL;

CREATE TABLE reader_invite_reward_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id bigint NOT NULL REFERENCES reader_invite_relations(id),
    inviter_reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    invitee_reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    reward_stage varchar(24) NOT NULL,
    reward_coin bigint NOT NULL,
    status varchar(16) NOT NULL,
    idempotency_key varchar(128) NOT NULL,
    granted_at timestamptz,
    remark varchar(255) NOT NULL DEFAULT '',
    source_type varchar(16) NOT NULL DEFAULT 'runtime',
    source_ref varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_invite_reward_records_stage_check CHECK (reward_stage IN ('register','first_recharge')),
    CONSTRAINT reader_invite_reward_records_amount_check CHECK (reward_coin >= 0),
    CONSTRAINT reader_invite_reward_records_status_check CHECK (status IN ('granted','skipped','failed')),
    CONSTRAINT reader_invite_reward_records_key_unique UNIQUE (idempotency_key)
);
CREATE INDEX reader_invite_reward_records_inviter_idx ON reader_invite_reward_records(inviter_reader_id,granted_at,id);
CREATE UNIQUE INDEX reader_invite_reward_records_legacy_source_uidx ON reader_invite_reward_records(source_type,source_ref) WHERE source_type='legacy' AND source_ref IS NOT NULL;

CREATE TABLE reader_wallet_adjustments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_no varchar(64) NOT NULL UNIQUE,
    reader_id bigint NOT NULL REFERENCES reader_accounts(id),
    coin_type varchar(16) NOT NULL,
    direction varchar(16) NOT NULL,
    amount bigint NOT NULL,
    reason varchar(255) NOT NULL,
    status varchar(16) NOT NULL,
    idempotency_key varchar(128) NOT NULL UNIQUE,
    operator_id bigint,
    operator_name varchar(64) NOT NULL DEFAULT '',
    ledger_id bigint REFERENCES reader_wallet_ledgers(id),
    source_type varchar(16) NOT NULL DEFAULT 'runtime',
    source_ref varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reader_wallet_adjustments_coin_check CHECK (coin_type IN ('recharge','bonus')),
    CONSTRAINT reader_wallet_adjustments_direction_check CHECK (direction IN ('increase','decrease')),
    CONSTRAINT reader_wallet_adjustments_amount_check CHECK (amount > 0),
    CONSTRAINT reader_wallet_adjustments_status_check CHECK (status IN ('confirmed','failed'))
);
CREATE INDEX reader_wallet_adjustments_reader_idx ON reader_wallet_adjustments(reader_id,created_at,id);
CREATE UNIQUE INDEX reader_wallet_adjustments_legacy_source_uidx ON reader_wallet_adjustments(source_type,source_ref) WHERE source_type='legacy' AND source_ref IS NOT NULL;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
