-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_book_profile_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auto_scan_enabled boolean NOT NULL DEFAULT false,
    auto_apply_enabled boolean NOT NULL DEFAULT false,
    process_ai_refusal_enabled boolean NOT NULL DEFAULT false,
    ai_config_id bigint NOT NULL REFERENCES novel_ai_config(id),
    refusal_fallback_ai_config_id bigint REFERENCES novel_ai_config(id),
    system_prompt text NOT NULL,
    temperature numeric(4,2) NOT NULL DEFAULT 0.10 CHECK (temperature BETWEEN 0 AND 2),
    max_tokens integer NOT NULL DEFAULT 2000 CHECK (max_tokens BETWEEN 1 AND 1000000),
    timeout_seconds integer NOT NULL DEFAULT 120 CHECK (timeout_seconds BETWEEN 1 AND 1800),
    request_interval_ms integer NOT NULL DEFAULT 0 CHECK (request_interval_ms BETWEEN 0 AND 600000),
    retry_count integer NOT NULL DEFAULT 1 CHECK (retry_count BETWEEN 0 AND 20),
    scan_batch_size integer NOT NULL DEFAULT 5 CHECK (scan_batch_size BETWEEN 1 AND 1000),
    max_input_chars integer NOT NULL DEFAULT 60000 CHECK (max_input_chars BETWEEN 1000 AND 1000000),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (refusal_fallback_ai_config_id IS NULL OR refusal_fallback_ai_config_id <> ai_config_id)
);
CREATE UNIQUE INDEX uq_novel_book_profile_config_singleton ON novel_book_profile_config ((true));

CREATE TABLE novel_book_profile_suggestion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL REFERENCES novel_books(id),
    status varchar(20) NOT NULL CHECK (status IN ('running','pending','approved','rejected','applied','failed','retried','recovered','expired')),
    trigger_type varchar(20) NOT NULL CHECK (trigger_type IN ('auto_scan','manual','regenerate')),
    input_mode varchar(32) NOT NULL CHECK (input_mode IN ('chapter_summary','chunk_summary','sampled_cleaned_text')),
    input_digest char(64) NOT NULL,
    input_snapshot jsonb NOT NULL,
    original_snapshot jsonb NOT NULL,
    suggested_snapshot jsonb,
    review_snapshot jsonb,
    raw_response text NOT NULL DEFAULT '',
    raw_response_expires_at timestamptz,
    reviewer_name varchar(100) NOT NULL DEFAULT '',
    reject_reason varchar(1000) NOT NULL DEFAULT '',
    reviewed_at timestamptz,
    applied_at timestamptz,
    error_message varchar(1000) NOT NULL DEFAULT '',
    failure_type varchar(64) NOT NULL DEFAULT '',
    retry_source_id bigint REFERENCES novel_book_profile_suggestion(id),
    retry_target_id bigint REFERENCES novel_book_profile_suggestion(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_novel_book_profile_blocking ON novel_book_profile_suggestion(book_id) WHERE status IN ('running','pending');
CREATE INDEX idx_novel_book_profile_list ON novel_book_profile_suggestion(status,created_at DESC,id DESC);
CREATE INDEX idx_novel_book_profile_book ON novel_book_profile_suggestion(book_id,id DESC);

INSERT INTO sys_base_menus
    (id,created_at,updated_at,menu_level,parent_id,path,name,hidden,component,sort,
     active_name,keep_alive,default_menu,title,icon,close_tab,transition_type)
VALUES (1723,now(),now(),2,1000,'novelBookProfile','NovelBookProfile',false,
    'view/novel/bookProfile/index.vue',69,'',true,false,'作品资料补全','edit-pen',false,'')
ON CONFLICT (id) DO NOTHING;
INSERT INTO sys_authority_menus(sys_base_menu_id,sys_authority_authority_id) VALUES(1723,888) ON CONFLICT DO NOTHING;

INSERT INTO sys_apis (id,created_at,updated_at,path,description,api_group,method) VALUES
    (1798,now(),now(),'/novel/bookProfile/config','查询作品资料补全配置','内容生产','GET'),
    (1799,now(),now(),'/novel/bookProfile/config','保存作品资料补全配置','内容生产','PUT'),
    (1800,now(),now(),'/novel/bookProfile/suggestions','查询作品资料建议','内容生产','GET'),
    (1801,now(),now(),'/novel/bookProfile/suggestions/:id','查询作品资料建议详情','内容生产','GET'),
    (1802,now(),now(),'/novel/bookProfile/suggestions','生成作品资料建议','内容生产','POST'),
    (1803,now(),now(),'/novel/bookProfile/suggestions/batch-regenerate','批量重试作品资料建议','内容生产','POST'),
    (1804,now(),now(),'/novel/bookProfile/suggestions/:id/reject','拒绝作品资料建议','内容生产','PUT'),
    (1805,now(),now(),'/novel/bookProfile/suggestions/:id/apply','应用作品资料建议','内容生产','PUT')
ON CONFLICT (id) DO NOTHING;
INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES
    ('p','888','/novel/bookProfile/config','GET','','',''),('p','888','/novel/bookProfile/config','PUT','','',''),
    ('p','888','/novel/bookProfile/suggestions','GET','','',''),('p','888','/novel/bookProfile/suggestions/:id','GET','','',''),
    ('p','888','/novel/bookProfile/suggestions','POST','','',''),('p','888','/novel/bookProfile/suggestions/batch-regenerate','POST','','',''),
    ('p','888','/novel/bookProfile/suggestions/:id/reject','PUT','','',''),('p','888','/novel/bookProfile/suggestions/:id/apply','PUT','','','')
ON CONFLICT DO NOTHING;
SELECT setval('sys_base_menus_id_seq',GREATEST((SELECT max(id) FROM sys_base_menus),1723),true);
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1805),true);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
