-- +goose Up
-- +goose StatementBegin
CREATE TABLE novel_chapter_summary_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled boolean NOT NULL DEFAULT false,
    ai_config_id bigint NOT NULL REFERENCES novel_ai_config(id),
    refusal_fallback_ai_config_id bigint REFERENCES novel_ai_config(id),
    system_prompt text NOT NULL,
    temperature numeric(4,2) NOT NULL DEFAULT 0.10 CHECK (temperature BETWEEN 0 AND 2),
    max_tokens integer NOT NULL DEFAULT 1000 CHECK (max_tokens BETWEEN 0 AND 1000000),
    max_input_chars integer NOT NULL DEFAULT 120000 CHECK (max_input_chars BETWEEN 1 AND 1000000),
    timeout_seconds integer NOT NULL DEFAULT 120 CHECK (timeout_seconds BETWEEN 1 AND 1800),
    request_interval_ms integer NOT NULL DEFAULT 0 CHECK (request_interval_ms BETWEEN 0 AND 600000),
    retry_count integer NOT NULL DEFAULT 1 CHECK (retry_count BETWEEN 0 AND 20),
    batch_size integer NOT NULL DEFAULT 50 CHECK (batch_size BETWEEN 1 AND 1000),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (refusal_fallback_ai_config_id IS NULL OR refusal_fallback_ai_config_id <> ai_config_id)
);
CREATE UNIQUE INDEX uq_novel_chapter_summary_singleton ON novel_chapter_summary_config ((true));

CREATE TABLE novel_chapter_summary_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(20) NOT NULL CHECK (status IN ('running','completed','stopped','failed')),
    automatic boolean NOT NULL DEFAULT false,
    total_count integer NOT NULL DEFAULT 0,
    processed_count integer NOT NULL DEFAULT 0,
    success_count integer NOT NULL DEFAULT 0,
    fail_count integer NOT NULL DEFAULT 0,
    current_result_id bigint REFERENCES novel_chapter_clean_result(id),
    current_book_id bigint REFERENCES novel_books(id),
    current_chapter_id bigint REFERENCES novel_chapters(id),
    stop_requested boolean NOT NULL DEFAULT false,
    operator_name varchar(64) NOT NULL DEFAULT '',
    error_summary varchar(1000) NOT NULL DEFAULT '',
    latest_error_message varchar(1000) NOT NULL DEFAULT '',
    latest_raw_response text NOT NULL DEFAULT '',
    raw_response_expires_at timestamptz,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_novel_chapter_summary_running ON novel_chapter_summary_task ((true)) WHERE status='running';
CREATE INDEX idx_novel_chapter_summary_task_status ON novel_chapter_summary_task(status,id DESC);

INSERT INTO sys_apis (id,created_at,updated_at,path,description,api_group,method) VALUES
    (1790,now(),now(),'/novel/chapterSummary/config','查询章节简介补全配置','内容生产','GET'),
    (1791,now(),now(),'/novel/chapterSummary/config','保存章节简介补全配置','内容生产','PUT'),
    (1792,now(),now(),'/novel/chapterSummary/status','查询章节简介补全状态','内容生产','GET'),
    (1793,now(),now(),'/novel/chapterSummary/tasks','查询章节简介补全任务','内容生产','GET'),
    (1794,now(),now(),'/novel/chapterSummary/tasks','启动章节简介补全任务','内容生产','POST'),
    (1795,now(),now(),'/novel/chapterSummary/tasks/:id/stop','停止章节简介补全任务','内容生产','POST'),
    (1796,now(),now(),'/novel/chapterSummary/tasks/:id/resume','续跑章节简介补全任务','内容生产','POST')
ON CONFLICT (id) DO NOTHING;

INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES
    ('p','888','/novel/chapterSummary/config','GET','','',''),
    ('p','888','/novel/chapterSummary/config','PUT','','',''),
    ('p','888','/novel/chapterSummary/status','GET','','',''),
    ('p','888','/novel/chapterSummary/tasks','GET','','',''),
    ('p','888','/novel/chapterSummary/tasks','POST','','',''),
    ('p','888','/novel/chapterSummary/tasks/:id/stop','POST','','',''),
    ('p','888','/novel/chapterSummary/tasks/:id/resume','POST','','','')
ON CONFLICT DO NOTHING;
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1796),true);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
