-- +goose Up
-- +goose StatementBegin
ALTER TABLE reader_payment_channels
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN display_name varchar(100) NOT NULL DEFAULT 'EPUSDT',
    ADD COLUMN merchant_pid_ciphertext text NOT NULL DEFAULT '',
    ADD COLUMN secret_ciphertext text NOT NULL DEFAULT '',
    ADD COLUMN create_url varchar(2048) NOT NULL DEFAULT '',
    ADD COLUMN notify_url varchar(2048) NOT NULL DEFAULT '',
    ADD COLUMN redirect_url varchar(2048) NOT NULL DEFAULT '',
    ADD COLUMN health_url varchar(2048) NOT NULL DEFAULT '',
    ADD COLUMN sync_url varchar(2048) NOT NULL DEFAULT '',
    ADD COLUMN connect_timeout_ms integer NOT NULL DEFAULT 3000,
    ADD COLUMN request_timeout_ms integer NOT NULL DEFAULT 10000,
    ADD COLUMN unknown_release_minutes integer NOT NULL DEFAULT 15,
    ADD COLUMN archived_at timestamptz,
    ADD COLUMN created_at timestamptz NOT NULL DEFAULT now();

SELECT setval(
    pg_get_serial_sequence('reader_payment_channels', 'id'),
    GREATEST((SELECT max(id) FROM reader_payment_channels), 1),
    true
);

ALTER TABLE reader_payment_channels DROP CONSTRAINT reader_payment_channels_provider_key;
ALTER TABLE reader_payment_channels
    ADD CONSTRAINT reader_payment_channels_provider_check CHECK (provider = 'epusdt'),
    ADD CONSTRAINT reader_payment_channels_asset_check CHECK (currency = 'usd' AND token = 'usdt' AND network = 'tron'),
    ADD CONSTRAINT reader_payment_channels_timeout_check CHECK (
        connect_timeout_ms BETWEEN 100 AND 30000
        AND request_timeout_ms BETWEEN connect_timeout_ms AND 120000
        AND unknown_release_minutes BETWEEN 1 AND 1440
    ),
    ADD CONSTRAINT reader_payment_channels_enabled_config_check CHECK (
        NOT enabled OR (
            archived_at IS NULL
            AND merchant_pid_ciphertext <> ''
            AND secret_ciphertext <> ''
            AND create_url <> ''
            AND notify_url <> ''
            AND redirect_url <> ''
            AND health_url <> ''
            AND sync_url <> ''
        )
    );
CREATE UNIQUE INDEX reader_payment_channels_active_provider_uidx
    ON reader_payment_channels(provider)
    WHERE archived_at IS NULL;

INSERT INTO sys_apis(id,created_at,updated_at,path,description,api_group,method) VALUES
(1823,now(),now(),'/reader/payment/channels/:id','查询支付渠道详情','读者支付','GET'),
(1824,now(),now(),'/reader/payment/channels','新增支付渠道','读者支付','POST'),
(1825,now(),now(),'/reader/payment/channels/:id','归档支付渠道','读者支付','DELETE')
ON CONFLICT DO NOTHING;
INSERT INTO casbin_rule(ptype,v0,v1,v2,v3,v4,v5) VALUES
('p','888','/reader/payment/channels/:id','GET','','',''),
('p','888','/reader/payment/channels','POST','','',''),
('p','888','/reader/payment/channels/:id','DELETE','','','')
ON CONFLICT DO NOTHING;
SELECT setval('sys_apis_id_seq',GREATEST((SELECT max(id) FROM sys_apis),1825),true);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Moonbook migrations are forward-only; create a higher corrective migration'; END $$;
-- +goose StatementEnd
