<template>
  <div class="gva-form-box products-page">
    <div class="page-head"><div><h2>消费商品</h2><p>维护书籍、章节、会员和免广告商品的价格及销售状态。</p></div><el-button type="primary" :icon="Plus" @click="openCreate">新增商品</el-button></div>
    <div class="toolbar"><el-input v-model="keyword" clearable placeholder="商品名称或目标 ID" @keyup.enter="load" /><el-select v-model="productType" clearable placeholder="商品类型" @change="load"><el-option v-for="item in productTypes" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-select v-model="saleStatus" clearable placeholder="销售状态" @change="load"><el-option label="在售" value="on_sale" /><el-option label="停售" value="off_sale" /></el-select><el-button :icon="Search" @click="load">查询</el-button></div>
    <el-table v-table-display v-loading="loading" :data="rows" border><el-table-column label="商品 ID" min-width="180"><template #default="{row}"><code>{{ row.id }}</code></template></el-table-column><el-table-column prop="productType" label="类型" width="110" /><el-table-column prop="targetId" label="关联作品 / 章节" min-width="180"><template #default="{row}"><code><BookReference v-if="row.productType === 'book'" :id="row.targetId || ''" /><span v-else>{{ row.targetId || '-' }}</span></code></template></el-table-column><el-table-column prop="productName" label="名称" min-width="180" /><el-table-column label="价格" width="110"><template #default="{row}"><code>{{ row.priceCoin }}</code></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.saleStatus === 'on_sale' ? 'success' : 'info'">{{ row.saleStatus === 'on_sale' ? '在售' : '停售' }}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-popconfirm title="确认删除该商品？" @confirm="remove(row)"><el-button link type="danger">删除</el-button></el-popconfirm></template></el-table-column></el-table>
    <div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @size-change="load" @current-change="load" /></div>
    <el-dialog v-model="dialog" :title="editing ? '编辑消费商品' : '新增消费商品'" width="540px"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-form-item label="商品类型" prop="productType"><el-select v-model="form.productType" :disabled="editing" @change="typeChanged"><el-option v-for="item in productTypes" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item v-if="needsTarget" label="关联作品 / 章节" prop="targetId"><BookSelect v-if="form.productType === 'book'" v-model="form.targetId" /><el-input v-else v-model="form.targetId" inputmode="numeric" placeholder="章节 ID" /></el-form-item><el-form-item label="商品名称" prop="productName"><el-input v-model="form.productName" maxlength="100" /></el-form-item><el-form-item label="价格（币）" prop="priceCoin"><el-input v-model="form.priceCoin" inputmode="numeric" /></el-form-item><el-form-item v-if="supportsDuration" label="有效期（天，留空为永久）"><el-input v-model="form.durationDays" inputmode="numeric" /></el-form-item><el-form-item label="允许奖励币抵扣"><el-switch v-model="form.allowBonusCoin" /></el-form-item><el-form-item label="销售状态" prop="saleStatus"><el-select v-model="form.saleStatus"><el-option label="在售" value="on_sale" /><el-option label="停售" value="off_sale" /></el-select></el-form-item><el-form-item label="排序"><el-input v-model="form.sortOrder" inputmode="numeric" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import BookSelect from '@/components/adminDisplay/BookSelect.vue'
import BookReference from '@/components/adminDisplay/BookReference.vue'
import { computed, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Plus, Search } from '@element-plus/icons-vue'
import { createProduct, deleteProduct, listProducts, updateProduct } from '@/api/reader/products'
defineOptions({ name: 'ReaderProducts' })
const productTypes = [{ value: 'book', label: '书籍' }, { value: 'chapter', label: '章节' }, { value: 'membership', label: '会员' }, { value: 'ad_free', label: '免广告' }]
const rows = ref([]); const total = ref(0); const page = ref(1); const pageSize = ref(20); const keyword = ref(''); const productType = ref(''); const saleStatus = ref(''); const loading = ref(false); const saving = ref(false); const dialog = ref(false); const editing = ref(false); const formRef = ref()
const form = reactive({ id: '', productType: 'book', targetId: '', productName: '', priceCoin: '', allowBonusCoin: false, durationDays: '', saleStatus: 'off_sale', sortOrder: '0' })
const needsTarget = computed(() => form.productType === 'book' || form.productType === 'chapter'); const supportsDuration = computed(() => form.productType === 'membership' || form.productType === 'ad_free')
const rules = { productType: [{ required: true, message: '请选择商品类型', trigger: 'change' }], targetId: [{ required: true, pattern: /^[1-9]\d*$/, message: '请输入正整数 ID', trigger: 'blur' }], productName: [{ required: true, message: '请输入商品名称', trigger: 'blur' }], priceCoin: [{ required: true, pattern: /^\d+$/, message: '请输入非负整数', trigger: 'blur' }], saleStatus: [{ required: true, message: '请选择销售状态', trigger: 'change' }] }
const load = async () => { loading.value = true; try { const res = await listProducts({ keyword: keyword.value, productType: productType.value, saleStatus: saleStatus.value, page: page.value, pageSize: pageSize.value }); rows.value = res.data?.list || []; total.value = res.data?.total || 0 } finally { loading.value = false } }
const reset = () => Object.assign(form, { id: '', productType: 'book', targetId: '', productName: '', priceCoin: '', allowBonusCoin: false, durationDays: '', saleStatus: 'off_sale', sortOrder: '0' })
const typeChanged = () => { form.targetId = ''; if (!supportsDuration.value) form.durationDays = '' }
const openCreate = () => { editing.value = false; reset(); dialog.value = true }
const openEdit = (row) => { editing.value = true; Object.assign(form, { id: row.id, productType: row.productType, targetId: row.targetId || '', productName: row.productName, priceCoin: row.priceCoin, allowBonusCoin: row.allowBonusCoin, durationDays: row.durationDays || '', saleStatus: row.saleStatus, sortOrder: String(row.sortOrder ?? 0) }); dialog.value = true }
const save = async () => { if (!(await formRef.value?.validate().catch(() => false))) return; saving.value = true; try { const payload = { productType: form.productType, targetId: needsTarget.value ? form.targetId : '', productName: form.productName, priceCoin: form.priceCoin, allowBonusCoin: form.allowBonusCoin, durationDays: supportsDuration.value && form.durationDays ? Number(form.durationDays) : null, saleStatus: form.saleStatus, sortOrder: Number(form.sortOrder || 0) }; if (editing.value) await updateProduct(form.id, payload); else await createProduct(payload); ElMessage.success('保存成功'); dialog.value = false; await load() } finally { saving.value = false } }
const remove = async (row) => { await deleteProduct(row.id); ElMessage.success('删除成功'); await load() }
load()
</script>
<style scoped>.products-page{padding:20px}.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.page-head h2{margin:0}.page-head p{margin:6px 0 0;color:var(--el-text-color-secondary)}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar .el-input{max-width:280px}.pager{display:flex;justify-content:flex-end;margin-top:16px}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}</style>
