global:
  resolve_timeout: 1m

route:
  receiver: local-webhook
  group_by: [alertname, severity, service]
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 4h

receivers:
  - name: local-webhook
    webhook_configs:
      - url: http://monitoring-webhook:8080/alerts
        send_resolved: true
