<template><div class="gva-form-box invite-page"><div class="page-head"><div><h2>邀请码</h2><p>生成和管理读者注册邀请码，已使用邀请码只能停用。</p></div><el-button type="primary" :icon="Plus" @click="openCreate">生成邀请码</el-button></div><div class="toolbar"><el-input v-model="keyword" clearable placeholder="搜索邀请码" @keyup.enter="load" /><el-button :icon="Search" @click="load">查询</el-button></div><el-table v-loading="loading" :data="rows" border><el-table-column label="邀请码 ID" min-width="180"><template #default="{ row }"><code>{{row.id}}</code></template></el-table-column><el-table-column prop="code" label="邀请码" min-width="180" /><el-table-column prop="status" label="状态" width="110" /><el-table-column label="使用次数" width="130"><template #default="{ row }">{{row.usedCount}} / {{row.maxUseCount || '不限'}}</template></el-table-column><el-table-column prop="expiresAt" label="过期时间" min-width="180" /><el-table-column label="操作" width="170"><template #default="{ row }"><el-switch :model-value="row.status === 'enabled'" :disabled="row.status === 'expired'" @change="toggle(row)" /><el-button link type="danger" :disabled="row.usedCount !== '0'" @click="remove(row)">删除</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @size-change="load" @current-change="load" /></div><el-dialog v-model="dialog" title="生成邀请码" width="460px"><el-form :model="form" label-position="top"><el-form-item label="自定义邀请码"><el-input v-model="form.code" maxlength="64" placeholder="留空则自动生成" /></el-form-item><el-form-item label="最大使用次数"><el-input v-model="form.maxUseCount" inputmode="numeric" placeholder="留空表示不限" /></el-form-item><el-form-item label="过期时间"><el-date-picker v-model="form.expiresAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">生成</el-button></template></el-dialog></div></template>
<script setup>
import { reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Search } from '@element-plus/icons-vue'
import { createInviteCode, deleteInviteCode, listInviteCodes, setInviteCodeStatus } from '@/api/reader/inviteCodes'
defineOptions({ name: 'ReaderInviteCodes' })
const rows=ref([]);const total=ref(0);const page=ref(1);const pageSize=ref(20);const keyword=ref('');const loading=ref(false);const dialog=ref(false);const saving=ref(false);const form=reactive({code:'',maxUseCount:'',expiresAt:''})
const load=async()=>{loading.value=true;try{const res=await listInviteCodes({keyword:keyword.value,page:page.value,pageSize:pageSize.value});rows.value=res.data?.list||[];total.value=res.data?.total||0}finally{loading.value=false}}
const openCreate=()=>{Object.assign(form,{code:'',maxUseCount:'',expiresAt:''});dialog.value=true}
const save=async()=>{saving.value=true;try{const res=await createInviteCode(form);ElMessage.success(`邀请码 ${res.data?.code || ''} 已生成`);dialog.value=false;await load()}finally{saving.value=false}}
const toggle=async(row)=>{const next=row.status==='enabled'?'disabled':'enabled';try{await setInviteCodeStatus(row.id,next);row.status=next;ElMessage.success('更新成功')}catch{} }
const remove=async(row)=>{await ElMessageBox.confirm('仅未使用的邀请码可以删除，确认继续？','删除确认');await deleteInviteCode(row.id);ElMessage.success('删除成功');await load()}
load()
</script><style scoped>.invite-page{padding:20px}.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.page-head h2{margin:0}.page-head p{margin:6px 0 0;color:var(--el-text-color-secondary)}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar .el-input{max-width:300px}.pager{display:flex;justify-content:flex-end;margin-top:16px}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}</style>
