<template><div class="gva-form-box"><div class="head"><div><h2>帖子候选</h2><p>审核论坛采集发现的帖子，导入任务会复用候选状态。</p></div></div><div class="toolbar"><el-input v-model="keyword" clearable placeholder="标题或帖子 ID" @keyup.enter="load"/><el-input v-model="sourceId" clearable placeholder="来源 ID" inputmode="numeric"/><el-input v-model="boardId" clearable placeholder="板块 ID" inputmode="numeric"/><el-select v-model="status" clearable placeholder="状态" @change="load"><el-option label="待导入" value="pending"/><el-option label="导入中" value="importing"/><el-option label="已导入" value="imported"/><el-option label="已跳过" value="skipped"/><el-option label="失败" value="failed"/></el-select><el-button :icon="Search" @click="load">查询</el-button></div><div class="actions"><el-button :disabled="!selected.length" @click="skip">跳过</el-button><el-button :disabled="!selected.length" @click="restore">恢复</el-button><el-button type="danger" plain :disabled="!selected.length" @click="remove">删除</el-button></div><el-table v-loading="loading" :data="rows" border @selection-change="selected=$event"><el-table-column type="selection" width="48"/><el-table-column label="候选 ID" width="170"><template #default="{row}"><code>{{row.id}}</code></template></el-table-column><el-table-column prop="sourceName" label="来源" width="130"/><el-table-column prop="boardName" label="板块" width="130"/><el-table-column label="标题" min-width="260"><template #default="{row}">{{row.displayTitle||row.threadTitle}}</template></el-table-column><el-table-column prop="forumThreadId" label="外部帖子 ID" width="150" show-overflow-tooltip/><el-table-column prop="status" label="状态" width="90"/><el-table-column prop="discoverTime" label="发现时间" width="180"/><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="detail(row)">详情</el-button><el-button link type="danger" :disabled="!['pending','skipped'].includes(row.status)" @click="remove([row.id])">删除</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @size-change="load" @current-change="load"/></div><el-dialog v-model="detailDialog" title="帖子候选详情" width="600px"><el-descriptions v-if="current" :column="1" border><el-descriptions-item label="候选 ID"><code>{{current.id}}</code></el-descriptions-item><el-descriptions-item label="来源 / 板块">{{current.sourceName}} / {{current.boardName}}</el-descriptions-item><el-descriptions-item label="标题">{{current.displayTitle||current.threadTitle}}</el-descriptions-item><el-descriptions-item label="帖子地址"><a :href="current.threadUrl" target="_blank" rel="noreferrer">{{current.threadUrl}}</a></el-descriptions-item><el-descriptions-item label="状态">{{current.status}}</el-descriptions-item><el-descriptions-item label="备注">{{current.remark||'-'}}</el-descriptions-item></el-descriptions></el-dialog></div></template>
<script setup>
import { ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search } from '@element-plus/icons-vue'
import { listCrawlCandidates, getCrawlCandidate, skipCrawlCandidates, restoreCrawlCandidates, deleteCrawlCandidates } from '@/api/novel/crawlCandidates'
defineOptions({ name: 'NovelCrawlCandidates' })
const rows=ref([]),selected=ref([]),total=ref(0),page=ref(1),pageSize=ref(20),keyword=ref(''),sourceId=ref(''),boardId=ref(''),status=ref(''),loading=ref(false),detailDialog=ref(false),current=ref(null)
const load=async()=>{loading.value=true;try{const r=await listCrawlCandidates({keyword:keyword.value,sourceId:sourceId.value,boardId:boardId.value,status:status.value,page:page.value,pageSize:pageSize.value});rows.value=r.data?.list||[];total.value=r.data?.total||0;selected.value=[]}finally{loading.value=false}}
const skip=async()=>{await skipCrawlCandidates(selected.value.map(r=>r.id));ElMessage.success('已跳过');load()};const restore=async()=>{await restoreCrawlCandidates(selected.value.map(r=>r.id));ElMessage.success('已恢复');load()}
const remove=async(ids)=>{try{await ElMessageBox.confirm('确定删除选中的帖子候选吗？','删除确认',{type:'warning'});await deleteCrawlCandidates(ids);ElMessage.success('删除成功');load()}catch{ElMessage.info('已取消删除')}}
const detail=async(row)=>{const r=await getCrawlCandidate(row.id);current.value=r.data;detailDialog.value=true};load()
</script>
<style scoped>.gva-form-box{padding:20px}.head{margin-bottom:18px}.head h2{margin:0}.head p{color:var(--el-text-color-secondary)}.toolbar,.actions{display:flex;gap:10px;margin-bottom:14px}.toolbar .el-input{max-width:220px}.pager{display:flex;justify-content:flex-end;margin-top:16px}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}a{color:var(--el-color-primary)}</style>
