<template><div class="gva-form-box"><div class="head"><div><h2>抓取日志</h2><p>审计论坛请求、解析阶段和失败详情。</p></div></div><div class="toolbar"><el-input v-model="keyword" clearable placeholder="请求地址或消息" @keyup.enter="load"/><el-input v-model="taskId" clearable placeholder="任务 ID" inputmode="numeric"/><el-select v-model="stage" clearable placeholder="阶段" @change="load"><el-option label="发现" value="discover"/><el-option label="帖子" value="thread"/><el-option label="章节" value="chapter"/><el-option label="导入" value="import"/><el-option label="质量" value="quality"/></el-select><el-select v-model="status" clearable placeholder="结果" @change="load"><el-option label="开始" value="started"/><el-option label="成功" value="succeeded"/><el-option label="失败" value="failed"/><el-option label="跳过" value="skipped"/></el-select><el-button :icon="Search" @click="load">查询</el-button></div><el-table v-loading="loading" :data="rows" border><el-table-column label="日志 ID" width="170"><template #default="{row}"><code>{{row.id}}</code></template></el-table-column><el-table-column prop="taskId" label="任务 ID" width="170"><template #default="{row}"><code>{{row.taskId||'-'}}</code></template></el-table-column><el-table-column prop="stage" label="阶段" width="90"/><el-table-column prop="status" label="结果" width="90"/><el-table-column prop="requestUrl" label="请求地址" min-width="260" show-overflow-tooltip/><el-table-column prop="httpStatus" label="HTTP" width="80"/><el-table-column prop="elapsedMs" label="耗时（毫秒）" width="110"/><el-table-column prop="createdAt" label="时间" width="180"/><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="detail(row)">详情</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @size-change="load" @current-change="load"/></div><el-dialog v-model="dialog" title="抓取日志详情" width="620px"><el-descriptions v-if="current" :column="1" border><el-descriptions-item label="日志 ID"><code>{{current.id}}</code></el-descriptions-item><el-descriptions-item label="阶段 / 结果">{{current.stage}} / {{current.status}}</el-descriptions-item><el-descriptions-item label="来源 / 板块">{{current.sourceName||'-'}} / {{current.boardName||'-'}}</el-descriptions-item><el-descriptions-item label="请求地址">{{current.requestUrl||'-'}}</el-descriptions-item><el-descriptions-item label="消息">{{current.message||'-'}}</el-descriptions-item><el-descriptions-item label="结构化详情"><pre>{{current.detailJson||'{}'}}</pre></el-descriptions-item></el-descriptions></el-dialog></div></template>
<script setup>
import { ref } from 'vue'
import { Search } from '@element-plus/icons-vue'
import { listCrawlFetchLogs, getCrawlFetchLog } from '@/api/novel/crawlFetchLogs'
defineOptions({ name: 'NovelCrawlFetchLogs' })
const rows=ref([]),total=ref(0),page=ref(1),pageSize=ref(20),keyword=ref(''),taskId=ref(''),stage=ref(''),status=ref(''),loading=ref(false),dialog=ref(false),current=ref(null)
const load=async()=>{loading.value=true;try{const r=await listCrawlFetchLogs({keyword:keyword.value,taskId:taskId.value,stage:stage.value,status:status.value,page:page.value,pageSize:pageSize.value});rows.value=r.data?.list||[];total.value=r.data?.total||0}finally{loading.value=false}}
const detail=async(row)=>{const r=await getCrawlFetchLog(row.id);current.value=r.data;dialog.value=true};load()
</script>
<style scoped>.gva-form-box{padding:20px}.head{margin-bottom:18px}.head h2{margin:0}.head p{color:var(--el-text-color-secondary)}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar .el-input{max-width:220px}.pager{display:flex;justify-content:flex-end;margin-top:16px}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}pre{white-space:pre-wrap;word-break:break-word}</style>
